export const allTableChartDevicePayload = {
  url: `${import.meta.env.VITE_API_DOMAIN}/api/v1/chart/data?form_data=%7B%22slice_id%22%3A924%7D&dashboard_id=54`,
  payload: {
    "datasource": {
      "id": 280,
      "type": "table"
    },
    "force": false,
    "queries": [
      {
        "time_range": "DATEADD(DATETIME(\"today\"),-2, DAY) : DATEADD(DATETIME(\"today\"),-1, SECOND)",
        "filters": [
          {
            "col": "date",
            "op": "TEMPORAL_RANGE",
            "val": "No filter"
          }
        ],
        "extras": {
          "having": "",
          "where": ""
        },
        "applied_time_extras": {},
        "columns": [
          "Tuần"
        ],
        "metrics": [
          {
            "aggregate": "SUM",
            "column": {
              "advanced_data_type": null,
              "certification_details": null,
              "certified_by": null,
              "column_name": "Tổng số spot",
              "description": null,
              "expression": null,
              "filterable": true,
              "groupby": true,
              "id": 6203,
              "is_certified": false,
              "is_dttm": false,
              "python_date_format": null,
              "type": "LONGLONG",
              "type_generic": 0,
              "verbose_name": null,
              "warning_markdown": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Tổng số spot",
            "optionName": "metric_8jy3jfndfny_1p4qpty26js",
            "sqlExpression": null
          },
          {
            "aggregate": "SUM",
            "column": {
              "advanced_data_type": null,
              "certification_details": null,
              "certified_by": null,
              "column_name": "Thời lượng (phút)",
              "description": null,
              "expression": null,
              "filterable": true,
              "groupby": true,
              "id": 6204,
              "is_certified": false,
              "is_dttm": false,
              "python_date_format": null,
              "type": "NEWDECIMAL",
              "type_generic": null,
              "verbose_name": null,
              "warning_markdown": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Thời lượng (phút)",
            "optionName": "metric_h2bs3bzsbib_zd5ldeam7bp",
            "sqlExpression": null
          },
          {
            "aggregate": "SUM",
            "column": {
              "advanced_data_type": null,
              "certification_details": null,
              "certified_by": null,
              "column_name": "Tổng số thiết bị ngày",
              "description": null,
              "expression": null,
              "filterable": true,
              "groupby": true,
              "id": 6205,
              "is_certified": false,
              "is_dttm": false,
              "python_date_format": null,
              "type": "LONGLONG",
              "type_generic": 0,
              "verbose_name": null,
              "warning_markdown": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Tổng số thiết bị",
            "optionName": "metric_futpebo0uph_9e9ng9lao37",
            "sqlExpression": null
          },
          {
            "aggregate": "AVG",
            "column": {
              "advanced_data_type": null,
              "certification_details": null,
              "certified_by": null,
              "column_name": "Reach 1+ (%)",
              "description": null,
              "expression": null,
              "filterable": true,
              "groupby": true,
              "id": 6206,
              "is_certified": false,
              "is_dttm": false,
              "python_date_format": null,
              "type": "NEWDECIMAL",
              "type_generic": null,
              "verbose_name": null,
              "warning_markdown": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Reach 1+ (%)",
            "optionName": "metric_byl21milwqg_xv3rewcikl8",
            "sqlExpression": null
          },
          {
            "aggregate": "AVG",
            "column": {
              "advanced_data_type": null,
              "certification_details": null,
              "certified_by": null,
              "column_name": "Reach 2+ (%)",
              "description": null,
              "expression": null,
              "filterable": true,
              "groupby": true,
              "id": 6207,
              "is_certified": false,
              "is_dttm": false,
              "python_date_format": null,
              "type": "NEWDECIMAL",
              "type_generic": null,
              "verbose_name": null,
              "warning_markdown": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Reach 2+ (%)",
            "optionName": "metric_pzyie0ux17k_4durgw2z0b7",
            "sqlExpression": null
          },
          {
            "aggregate": "AVG",
            "column": {
              "advanced_data_type": null,
              "certification_details": null,
              "certified_by": null,
              "column_name": "Reach 3+ (%)",
              "description": null,
              "expression": null,
              "filterable": true,
              "groupby": true,
              "id": 6208,
              "is_certified": false,
              "is_dttm": false,
              "python_date_format": null,
              "type": "NEWDECIMAL",
              "type_generic": null,
              "verbose_name": null,
              "warning_markdown": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Reach 3+ (%)",
            "optionName": "metric_lq6hs8uswcp_0hmn6n1daozi",
            "sqlExpression": null
          }
        ],
        "orderby": [
          [
            {
              "aggregate": "SUM",
              "column": {
                "advanced_data_type": null,
                "certification_details": null,
                "certified_by": null,
                "column_name": "Tổng số spot",
                "description": null,
                "expression": null,
                "filterable": true,
                "groupby": true,
                "id": 6203,
                "is_certified": false,
                "is_dttm": false,
                "python_date_format": null,
                "type": "LONGLONG",
                "type_generic": 0,
                "verbose_name": null,
                "warning_markdown": null
              },
              "datasourceWarning": false,
              "expressionType": "SIMPLE",
              "hasCustomLabel": true,
              "label": "Tổng số spot",
              "optionName": "metric_8jy3jfndfny_1p4qpty26js",
              "sqlExpression": null
            },
            false
          ]
        ],
        "annotation_layers": [],
        "row_limit": 50000,
        "series_limit": 0,
        "order_desc": false,
        "url_params": {
          "native_filters_key": "RZrfP_eeog2mTDl53H8v6vhGuUt4rlQRkFcDtSUffkkyAjOhiINk_3W4QyrQ3z-_"
        },
        "custom_params": {},
        "custom_form_data": {},
        "post_processing": [],
        "time_offsets": []
      }
    ],
    "form_data": {
      "datasource": "280__table",
      "viz_type": "table",
      "slice_id": 924,
      "url_params": {
        "native_filters_key": "RZrfP_eeog2mTDl53H8v6vhGuUt4rlQRkFcDtSUffkkyAjOhiINk_3W4QyrQ3z-_"
      },
      "query_mode": "aggregate",
      "groupby": [
        "Tuần"
      ],
      "temporal_columns_lookup": {
        "date": true
      },
      "metrics": [
        {
          "aggregate": "SUM",
          "column": {
            "advanced_data_type": null,
            "certification_details": null,
            "certified_by": null,
            "column_name": "Tổng số spot",
            "description": null,
            "expression": null,
            "filterable": true,
            "groupby": true,
            "id": 6203,
            "is_certified": false,
            "is_dttm": false,
            "python_date_format": null,
            "type": "LONGLONG",
            "type_generic": 0,
            "verbose_name": null,
            "warning_markdown": null
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": true,
          "label": "Tổng số spot",
          "optionName": "metric_8jy3jfndfny_1p4qpty26js",
          "sqlExpression": null
        },
        {
          "aggregate": "SUM",
          "column": {
            "advanced_data_type": null,
            "certification_details": null,
            "certified_by": null,
            "column_name": "Thời lượng (phút)",
            "description": null,
            "expression": null,
            "filterable": true,
            "groupby": true,
            "id": 6204,
            "is_certified": false,
            "is_dttm": false,
            "python_date_format": null,
            "type": "NEWDECIMAL",
            "type_generic": null,
            "verbose_name": null,
            "warning_markdown": null
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": true,
          "label": "Thời lượng (phút)",
          "optionName": "metric_h2bs3bzsbib_zd5ldeam7bp",
          "sqlExpression": null
        },
        {
          "aggregate": "SUM",
          "column": {
            "advanced_data_type": null,
            "certification_details": null,
            "certified_by": null,
            "column_name": "Tổng số thiết bị ngày",
            "description": null,
            "expression": null,
            "filterable": true,
            "groupby": true,
            "id": 6205,
            "is_certified": false,
            "is_dttm": false,
            "python_date_format": null,
            "type": "LONGLONG",
            "type_generic": 0,
            "verbose_name": null,
            "warning_markdown": null
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": true,
          "label": "Tổng số thiết bị",
          "optionName": "metric_futpebo0uph_9e9ng9lao37",
          "sqlExpression": null
        },
        {
          "aggregate": "AVG",
          "column": {
            "advanced_data_type": null,
            "certification_details": null,
            "certified_by": null,
            "column_name": "Reach 1+ (%)",
            "description": null,
            "expression": null,
            "filterable": true,
            "groupby": true,
            "id": 6206,
            "is_certified": false,
            "is_dttm": false,
            "python_date_format": null,
            "type": "NEWDECIMAL",
            "type_generic": null,
            "verbose_name": null,
            "warning_markdown": null
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": true,
          "label": "Reach 1+ (%)",
          "optionName": "metric_byl21milwqg_xv3rewcikl8",
          "sqlExpression": null
        },
        {
          "aggregate": "AVG",
          "column": {
            "advanced_data_type": null,
            "certification_details": null,
            "certified_by": null,
            "column_name": "Reach 2+ (%)",
            "description": null,
            "expression": null,
            "filterable": true,
            "groupby": true,
            "id": 6207,
            "is_certified": false,
            "is_dttm": false,
            "python_date_format": null,
            "type": "NEWDECIMAL",
            "type_generic": null,
            "verbose_name": null,
            "warning_markdown": null
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": true,
          "label": "Reach 2+ (%)",
          "optionName": "metric_pzyie0ux17k_4durgw2z0b7",
          "sqlExpression": null
        },
        {
          "aggregate": "AVG",
          "column": {
            "advanced_data_type": null,
            "certification_details": null,
            "certified_by": null,
            "column_name": "Reach 3+ (%)",
            "description": null,
            "expression": null,
            "filterable": true,
            "groupby": true,
            "id": 6208,
            "is_certified": false,
            "is_dttm": false,
            "python_date_format": null,
            "type": "NEWDECIMAL",
            "type_generic": null,
            "verbose_name": null,
            "warning_markdown": null
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": true,
          "label": "Reach 3+ (%)",
          "optionName": "metric_lq6hs8uswcp_0hmn6n1daozi",
          "sqlExpression": null
        }
      ],
      "all_columns": [],
      "percent_metrics": [],
      "adhoc_filters": [
        {
          "clause": "WHERE",
          "comparator": "No filter",
          "expressionType": "SIMPLE",
          "isExtra": true,
          "operator": "TEMPORAL_RANGE",
          "subject": "date"
        }
      ],
      "order_by_cols": [],
      "row_limit": 50000,
      "server_page_length": 10,
      "order_desc": false,
      "table_timestamp_format": "smart_date",
      "include_search": true,
      "allow_render_html": true,
      "column_config": {
        "Tổng số thiết bị": {
          "d3NumberFormat": ",d"
        }
      },
      "show_cell_bars": true,
      "color_pn": true,
      "comparison_color_scheme": "Green",
      "conditional_formatting": [],
      "comparison_type": "values",
      "dashboards": [],
      "extra_form_data": {
        "time_range": "DATEADD(DATETIME(\"today\"),-2, DAY) : DATEADD(DATETIME(\"today\"),-1, SECOND)"
      },
      "chart_id": 924,
      "label_colors": {
        "price": "#ffd04c",
        "price_usd": "#ffd04c",
        "count": "#ffd04c",
        "VTV1": "#ca2d1e",
        "VTV2": "#42932b",
        "VTV3": "#000191",
        "VTV5": "#9467bd",
        "VTV Cần Thơ": "#6ce5e8",
        "VTV4": "#8c564b",
        "VTV9": "#e377c2",
        "VTV5 Tây Nam Bộ": "#7f7f7f",
        "VTV8": "#bcbd22",
        "VTV7": "#2d8bba",
        "Thời sự - Chính luận": "#6BD3B3",
        "Phim dài tập": "#FCC550",
        "Đời sống": "#EE5960",
        "Tài liệu - Phóng sự": "#408184",
        "Giải trí": "#66CBE2",
        "Giáo dục - Đào tạo": "#5470C6",
        "Dành cho trẻ em": "#ffb2f3",
        "Thể thao": "#FF874E",
        "Sự kiện": "#03748E",
        "Quảng bá": "#8c564a",
        "Phim truyện": "#C9BBAB",
        "Quảng cáo": "#B17BAA"
      },
      "shared_label_colors": [
        "7UP (AERATED SO...",
        "AGRIBANK",
        "AJINOMOTO VIETN...",
        "ALIPAS (MEN SUP...",
        "ANTOT THYMO",
        "AVENUE",
        "BAMBOO-AIRWAYS",
        "BAO KHI KHANG (...",
        "BIA HA NOI",
        "BINH DIEN FERTI...",
        "BINH VI THAI MI...",
        "BOGANIC PREMIUM...",
        "BONCHA (RTD GRE...",
        "BONISLEEP (ANTI...",
        "BOSS COFFEE (RT...",
        "BRIGHT PARK",
        "BYEBYE-FYVER",
        "C2 (RTD GREEN T...",
        "CA HOI NA UY SF...",
        "CASPER (AIR CON...",
        "CHARMORA CITY N...",
        "CHIN-SU (CHILI ...",
        "CLEAR MAT LANH",
        "CLEAR MEN (MEN ...",
        "CLOSEUP BAC HA",
        "COLGATE (TOOTHP...",
        "COMFORT (FABRIC...",
        "COOL AIR",
        "CTY TNHH TAP DO...",
        "CTY TNHH TM XNK...",
        "DA HUONG (FEMIN...",
        "DANISA",
        "DAT VIET CERAMI...",
        "DAU TRAU (FERTI...",
        "DONG TRUNG HA T...",
        "DOVE (HAIR CARE...",
        "DR.THANH (RTD H...",
        "DREAME",
        "DUNG DICH XIT H...",
        "DUTCH LADY OMEG...",
        "ENCHANTEUR (SHO...",
        "ENSURE (NUTRITI...",
        "ENTEROGERMINA (...",
        "FLC PREMIER PAR...",
        "FPT LONG CHAU P...",
        "FUZE TEA",
        "Giáo dục - Đào tạo",
        "Giải trí",
        "HANOI (BEER)",
        "HDBANK PRIORITY",
        "HOA PHAT (TOLE)",
        "HOA PHAT STEEL ...",
        "HOA SEN MAG SHI...",
        "HOAT HUYET DUON...",
        "HOAT HUYET THON...",
        "HONDA CUVE",
        "HONG SAM VIET N...",
        "HUU CO PHU MY O...",
        "HYGIENE (FABRIC...",
        "HYUNDAI-SANTAFE...",
        "ICH NIEU KHANG ...",
        "IPHONE - APPLE ...",
        "JEX (BONE & JOI...",
        "JOGARBOLA",
        "KANGAROO (WATER...",
        "KATIA PREMIUM V...",
        "KHUONG THAO DAN...",
        "KIEN TRUC NOI T...",
        "KINGSUP (MEN SU...",
        "KNORR",
        "KNORR (SEASONIN...",
        "KOKOMI SNACKING",
        "LEE KUM KEE",
        "LINEABON (VITAM...",
        "LIPOVITAN",
        "LOCPHAT PAY",
        "LOTTE CHOCOLAT",
        "LPBANK",
        "LPBANK VISA",
        "MANULIFE",
        "MASTER MEDIA AC...",
        "MAZDA CX-5 (COM...",
        "MB (BANK)",
        "MEAT DELI (PORK...",
        "MERIVISTA",
        "MIK GROUP",
        "MILO (ENERGY PO...",
        "MOC CHAU CREAME...",
        "MOLFIX OXY",
        "MOOZI",
        "NAGAKAWA (AIR C...",
        "NAM NGU (FISH S...",
        "NEWTOWN DIAMOND...",
        "NEXTG CAL (VITA...",
        "NGOC CHAU (TOOT...",
        "NGUYEN XUAN (HE...",
        "NUI THAN TAI MI...",
        "NUMBER 1 (ENERG...",
        "NUMBER 1- 0 DO ...",
        "NUOC TANG LUC 4...",
        "NUTRI BOOST (FL...",
        "OMACHI (INSTANT...",
        "OMO (WASHING LI...",
        "OPTIMUM COLOS (...",
        "OREO (BISCUIT)",
        "P/S (TOOTHPASTE...",
        "PANADOL (COUGHS...",
        "PEPSI (AERATED ...",
        "PETRO VIETNAM (...",
        "PETROLIMEX VIET...",
        "PEUGEOT 408 (MI...",
        "PLEIKU GOLF CLU...",
        "PONNIE",
        "POWER OF SUN",
        "PSA",
        "PV GAS - PETROV...",
        "PVCOMBANK",
        "Phim dài tập",
        "Quảng cáo",
        "RANG DONG",
        "RED BULL (ENERG...",
        "REJOICE (SHAMPO...",
        "ROMA D-MAXX MAR...",
        "ROMANO (MEN SHA...",
        "SACOMBANK APPLE...",
        "SALONPAS (PAIN ...",
        "SAM NHUNG BO TH...",
        "SCTV CHANNELS (...",
        "SEABANK",
        "SEAPAYMENT",
        "SENSODYNE (TOOT...",
        "SODA",
        "STING (ENERGY D...",
        "SUA RUA MAT LEN...",
        "SUBAC (ANTISEPT...",
        "SUMIKURA",
        "SUN FESTO TOWN",
        "SUN GROUP VIETN...",
        "SUNLIGHT (DISH ...",
        "SUNSHINE BAY RE...",
        "SUNSILK (HAIR C...",
        "SUOI TIEN (THEM...",
        "TAM BINH (DRINK...",
        "TEA+ (RTD OLONG...",
        "TEBAGOCEL",
        "TECHCOMBANK",
        "TH TRUE FOOD (F...",
        "TH TRUE MILK (F...",
        "THACO LOGISTICS",
        "THANH HANG BEAU...",
        "THE MAGNOLIA PR...",
        "THE PARKLAND",
        "THEP VAS",
        "TROPICANA TWIST...",
        "TRUONG HAI AUTO...",
        "Thể thao",
        "Thời sự - Chính luận",
        "UNIQLO (FASHION...",
        "VF8",
        "VIETINBANK",
        "VIETLOTT (LOTTE...",
        "VIETNAM AIRLINE...",
        "VIGLACERA",
        "VIGLACERA (CERA...",
        "VIGLACERA KINH ...",
        "VILAZA",
        "VINAMILK",
        "VINAMILK (EATIN...",
        "VINAMILK (FRESH...",
        "VINAMILK (NUT M...",
        "VINFAST",
        "VINHOMES GLOBAL...",
        "VINHOMES GREEN ...",
        "VINHOMES HAI VA...",
        "VINMEC HEALTHCA...",
        "VPBANK",
        "VPBANK (CREDIT ...",
        "VPBANK - APPLE ...",
        "VPBANK SECURITI...",
        "VPP HAI TIEN",
        "VTV1",
        "VTV2",
        "VTV3",
        "VTV6",
        "VTV8",
        "VTV9",
        "VUONG BAO (PROS...",
        "Vui lòng chọn filter Brand",
        "X-MEN (MEN SHAM...",
        "YAKULT (DRINKIN...",
        "YAMAHA",
        "YOMOST",
        "YUMANGEL (STOMA...",
        "ZOZO IMUSE (COL...",
        "price",
        "Đời sống"
      ],
      "map_label_colors": {
        "SMART_TV": "#1FA8C9",
        "MOBILE": "#454E7C",
        "PC/Lap": "#5AC189",
        "TABLET": "#FF7F44",
        "TECHCOMBANK": "#1FA8C9",
        "VINHOMES HAI VA...": "#454E7C",
        "AVENUE": "#5AC189",
        "VINHOMES GLOBAL...": "#FF7F44",
        "VINAMILK (FRESH...": "#E04355",
        "YAMAHA": "#666666",
        "IPHONE - APPLE ...": "#8FD3E4",
        "DANISA": "#FCC700",
        "MIK GROUP": "#A868B7",
        "VPP HAI TIEN": "#3CCCCB",
        "AJINOMOTO VIETN...": "#A38F79",
        "OMACHI (INSTANT...": "#8fb1e4",
        "VPBANK": "#A1A6BD",
        "MEAT DELI (PORK...": "#FCC700",
        "CASPER (AIR CON...": "#ACE1C4",
        "NGUYEN XUAN (HE...": "#9ed0e5",
        "HOAT HUYET DUON...": "#d1cebc",
        "DA HUONG (FEMIN...": "#FEC0A1",
        "SUA RUA MAT LEN...": "#a2a379",
        "VINAMILK": "#B2B2B2",
        "PONNIE": "#d1cabc",
        "TAM BINH (DRINK...": "#FEC0A1",
        "HONDA CUVE": "#EFA1AA",
        "VINFAST": "#FDE380",
        "VINHOMES GREEN ...": "#D3B3DA",
        "NEXTG CAL (VITA...": "#9EE5E5",
        "SUN FESTO TOWN": "#D1C6BC",
        "SUN GROUP VIETN...": "#9EE5E5",
        "NUMBER 1 (ENERG...": "#1f86c9",
        "NUMBER 1- 0 DO ...": "#feeea1",
        "SENSODYNE (TOOT...": "#D1C6BC",
        "OMO (WASHING LI...": "#b7689e",
        "CA HOI NA UY SF...": "#47457c",
        "HOA PHAT STEEL ...": "#FDE380",
        "C2 (RTD GREEN T...": "#5ac19e",
        "BOGANIC PREMIUM...": "#45537c",
        "DUNG DICH XIT H...": "#3c93cc",
        "BOSS COFFEE (RT...": "#ffa444",
        "LOTTE CHOCOLAT": "#47457c",
        "MOOZI": "#e05043",
        "MILO (ENERGY PO...": "#efa8a1",
        "VIETLOTT (LOTTE...": "#fcf900",
        "KHUONG THAO DAN...": "#b768b6",
        "RED BULL (ENERG...": "#3CCCCB",
        "BINH VI THAI MI...": "#fcf900",
        "BAO KHI KHANG (...": "#1f75c9",
        "ENTEROGERMINA (...": "#3cb0cc",
        "BONCHA (RTD GRE...": "#454e7c",
        "ROMA D-MAXX MAR...": "#9EE5E5",
        "FUZE TEA": "#b768ae",
        "THE PARKLAND": "#a39779",
        "THE MAGNOLIA PR...": "#8fc2e4",
        "ICH NIEU KHANG ...": "#f1fd80",
        "VIGLACERA": "#a2a1bd",
        "SUMIKURA": "#ace1cf",
        "YAKULT (DRINKIN...": "#e06043",
        "THEP VAS": "#e05043",
        "MASTER MEDIA AC...": "#fed3a1",
        "COMFORT (FABRIC...": "#b3fc00",
        "SUNLIGHT (DISH ...": "#efafa1",
        "TEA+ (RTD OLONG...": "#a39779",
        "THANH HANG BEAU...": "#fed3a1",
        "VINAMILK (NUT M...": "#dab3d5",
        "COLGATE (TOOTHP...": "#D3B3DA",
        "VIETINBANK": "#b2b2b2",
        "HANOI (BEER)": "#fdfc80",
        "JEX (BONE & JOI...": "#45497c",
        "BYEBYE-FYVER": "#a7a1bd",
        "VUONG BAO (PROS...": "#8fc2e4",
        "CLEAR MEN (MEN ...": "#dab3d9",
        "OREO (BISCUIT)": "#9ed7e5",
        "PETRO VIETNAM (...": "#fdfc80",
        "MB (BANK)": "#dab3d9",
        "VIGLACERA KINH ...": "#9ed7e5",
        "DREAME": "#1f97c9",
        "CLEAR MAT LANH": "#a4a1bd",
        "MOLFIX OXY": "#A1A6BD",
        "NUI THAN TAI MI...": "#1fa8c9",
        "TROPICANA TWIST...": "#5ac193",
        "ROMANO (MEN SHA...": "#5ac19e",
        "YUMANGEL (STOMA...": "#ff9244",
        "PSA": "#4c457c",
        "SALONPAS (PAIN ...": "#ace1d9",
        "VIETNAM AIRLINE...": "#a2a1bd",
        "LEE KUM KEE": "#5ac1a8",
        "BIA HA NOI": "#a39c79",
        "DONG TRUNG HA T...": "#ffb744",
        "STING (ENERGY D...": "#e5fc00",
        "X-MEN (MEN SHAM...": "#ffb744",
        "VPBANK - APPLE ...": "#e04345",
        "SCTV CHANNELS (...": "#d1ccbc",
        "DOVE (HAIR CARE...": "#52457c",
        "7UP (AERATED SO...": "#9ed7e5",
        "COOL AIR": "#fce000",
        "KNORR (SEASONIN...": "#b068b7",
        "VIGLACERA (CERA...": "#3cbfcc",
        "VINAMILK (EATIN...": "#57457c",
        "PV GAS - PETROV...": "#3ca2cc",
        "AGRIBANK": "#a39379",
        "TEBAGOCEL": "#8fb9e4",
        "Chưa xem hết": "#6BD3B3",
        "Xem hết": "#FCC550",
        "COUNT_DISTINCT(prd)": "#6BD3B3",
        "Vui lòng chọn filter Brand": "#FCC550",
        "COUNT_DISTINCT(gr)": "#6BD3B3"
      },
      "extra_filters": [],
      "force": false,
      "result_format": "json",
      "result_type": "full",
      heavy: true
    },
    "result_format": "json",
    "result_type": "full"
  }
};