export const allTableChartPlatformPayload = {
  url: `${import.meta.env.VITE_API_DOMAIN}/api/v1/chart/data?form_data=%7B%22slice_id%22%3A865%7D&dashboard_id=55`,
  payload: {
    "datasource": {
      "id": 251,
      "type": "table"
    },
    "force": false,
    "queries": [
      {
        "time_range": "DATEADD(DATETIME(\"today\"),-2, DAY) : DATEADD(DATETIME(\"today\"),-1, SECOND)",
        "filters": [
          {
            "col": "date",
            "op": "TEMPORAL_RANGE",
            "val": "No filter"
          }
        ],
        "extras": {
          "having": "",
          "where": ""
        },
        "applied_time_extras": {},
        "columns": [
          "Tuần",
          "Thiết bị"
        ],
        "metrics": [
          {
            "aggregate": "SUM",
            "column": {
              "advanced_data_type": null,
              "changed_on": "2025-12-25T13:32:45.770590",
              "column_name": "Active device",
              "created_on": "2025-12-25T13:32:45.770585",
              "description": null,
              "expression": null,
              "extra": "{}",
              "filterable": true,
              "groupby": true,
              "id": 4845,
              "is_active": true,
              "is_dttm": false,
              "python_date_format": null,
              "type": "LONGLONG",
              "type_generic": 0,
              "uuid": "46668a0f-b53b-46b2-b0d5-c98ba6f1f44e",
              "verbose_name": "Tổng số thiết bị ngày"
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Tổng user truy cập VTVgo",
            "optionName": "metric_l5vzjwveaf_xvzuz04t0j",
            "sqlExpression": null
          },
          {
            "aggregate": "SUM",
            "column": {
              "advanced_data_type": null,
              "changed_on": "2025-12-25T13:32:45.770636",
              "column_name": "REACH 1+",
              "created_on": "2025-12-25T13:32:45.770634",
              "description": null,
              "expression": null,
              "extra": "{}",
              "filterable": true,
              "groupby": true,
              "id": 4846,
              "is_active": true,
              "is_dttm": false,
              "python_date_format": null,
              "type": "NEWDECIMAL",
              "type_generic": null,
              "uuid": "6716e43d-1f8e-4359-baf9-e79743469473",
              "verbose_name": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Reach 1+ (%)",
            "optionName": "metric_z1a4z4qvw2p_iqaz5sao45s",
            "sqlExpression": null
          },
          {
            "aggregate": "SUM",
            "column": {
              "advanced_data_type": null,
              "changed_on": "2025-12-25T13:32:45.770663",
              "column_name": "REACH 2+",
              "created_on": "2025-12-25T13:32:45.770661",
              "description": null,
              "expression": null,
              "extra": "{}",
              "filterable": true,
              "groupby": true,
              "id": 4847,
              "is_active": true,
              "is_dttm": false,
              "python_date_format": null,
              "type": "NEWDECIMAL",
              "type_generic": null,
              "uuid": "f2ed031f-a7e4-4338-87ff-ff8d6e0b5a67",
              "verbose_name": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Reach 2+ (%)",
            "optionName": "metric_b8r9caxbafd_lle1ovp8qtp",
            "sqlExpression": null
          },
          {
            "aggregate": "SUM",
            "column": {
              "advanced_data_type": null,
              "changed_on": "2025-12-25T13:32:45.770692",
              "column_name": "REACH 3+",
              "created_on": "2025-12-25T13:32:45.770690",
              "description": null,
              "expression": null,
              "extra": "{}",
              "filterable": true,
              "groupby": true,
              "id": 4848,
              "is_active": true,
              "is_dttm": false,
              "python_date_format": null,
              "type": "NEWDECIMAL",
              "type_generic": null,
              "uuid": "06fc0e16-1891-43e2-ad84-98caaa05b32f",
              "verbose_name": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Reach 3+ (%)",
            "optionName": "metric_q3dqccgnmms_kv9v2rkjsdo",
            "sqlExpression": null
          }
        ],
        "orderby": [
          [
            {
              "aggregate": "MIN",
              "column": {
                "advanced_data_type": null,
                "certification_details": null,
                "certified_by": null,
                "column_name": "Tuần",
                "description": null,
                "expression": null,
                "filterable": true,
                "groupby": true,
                "id": 4851,
                "is_certified": false,
                "is_dttm": false,
                "python_date_format": null,
                "type": "STRING",
                "type_generic": 1,
                "verbose_name": null,
                "warning_markdown": null
              },
              "datasourceWarning": false,
              "expressionType": "SIMPLE",
              "hasCustomLabel": false,
              "label": "MIN(Tuần)",
              "optionName": "metric_qag9nk6gnl_hx1pvh4bpdm",
              "sqlExpression": null
            },
            false
          ]
        ],
        "annotation_layers": [],
        "row_limit": 1000,
        "series_limit": 0,
        "series_limit_metric": {
          "aggregate": "MIN",
          "column": {
            "advanced_data_type": null,
            "certification_details": null,
            "certified_by": null,
            "column_name": "Tuần",
            "description": null,
            "expression": null,
            "filterable": true,
            "groupby": true,
            "id": 4851,
            "is_certified": false,
            "is_dttm": false,
            "python_date_format": null,
            "type": "STRING",
            "type_generic": 1,
            "verbose_name": null,
            "warning_markdown": null
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": false,
          "label": "MIN(Tuần)",
          "optionName": "metric_qag9nk6gnl_hx1pvh4bpdm",
          "sqlExpression": null
        },
        "order_desc": true,
        "url_params": {},
        "custom_params": {},
        "custom_form_data": {},
        "post_processing": [],
        "time_offsets": []
      }
    ],
    "form_data": {
      "datasource": "251__table",
      "viz_type": "table",
      "slice_id": 865,
      "url_params": {},
      "query_mode": "aggregate",
      "groupby": [
        "Tuần",
        "Thiết bị"
      ],
      "temporal_columns_lookup": {},
      "metrics": [
        {
          "aggregate": "SUM",
          "column": {
            "advanced_data_type": null,
            "changed_on": "2025-12-25T13:32:45.770590",
            "column_name": "Active device",
            "created_on": "2025-12-25T13:32:45.770585",
            "description": null,
            "expression": null,
            "extra": "{}",
            "filterable": true,
            "groupby": true,
            "id": 4845,
            "is_active": true,
            "is_dttm": false,
            "python_date_format": null,
            "type": "LONGLONG",
            "type_generic": 0,
            "uuid": "46668a0f-b53b-46b2-b0d5-c98ba6f1f44e",
            "verbose_name": "Tổng số thiết bị ngày"
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": true,
          "label": "Tổng user truy cập VTVgo",
          "optionName": "metric_l5vzjwveaf_xvzuz04t0j",
          "sqlExpression": null
        },
        {
          "aggregate": "SUM",
          "column": {
            "advanced_data_type": null,
            "changed_on": "2025-12-25T13:32:45.770636",
            "column_name": "REACH 1+",
            "created_on": "2025-12-25T13:32:45.770634",
            "description": null,
            "expression": null,
            "extra": "{}",
            "filterable": true,
            "groupby": true,
            "id": 4846,
            "is_active": true,
            "is_dttm": false,
            "python_date_format": null,
            "type": "NEWDECIMAL",
            "type_generic": null,
            "uuid": "6716e43d-1f8e-4359-baf9-e79743469473",
            "verbose_name": null
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": true,
          "label": "Reach 1+ (%)",
          "optionName": "metric_z1a4z4qvw2p_iqaz5sao45s",
          "sqlExpression": null
        },
        {
          "aggregate": "SUM",
          "column": {
            "advanced_data_type": null,
            "changed_on": "2025-12-25T13:32:45.770663",
            "column_name": "REACH 2+",
            "created_on": "2025-12-25T13:32:45.770661",
            "description": null,
            "expression": null,
            "extra": "{}",
            "filterable": true,
            "groupby": true,
            "id": 4847,
            "is_active": true,
            "is_dttm": false,
            "python_date_format": null,
            "type": "NEWDECIMAL",
            "type_generic": null,
            "uuid": "f2ed031f-a7e4-4338-87ff-ff8d6e0b5a67",
            "verbose_name": null
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": true,
          "label": "Reach 2+ (%)",
          "optionName": "metric_b8r9caxbafd_lle1ovp8qtp",
          "sqlExpression": null
        },
        {
          "aggregate": "SUM",
          "column": {
            "advanced_data_type": null,
            "changed_on": "2025-12-25T13:32:45.770692",
            "column_name": "REACH 3+",
            "created_on": "2025-12-25T13:32:45.770690",
            "description": null,
            "expression": null,
            "extra": "{}",
            "filterable": true,
            "groupby": true,
            "id": 4848,
            "is_active": true,
            "is_dttm": false,
            "python_date_format": null,
            "type": "NEWDECIMAL",
            "type_generic": null,
            "uuid": "06fc0e16-1891-43e2-ad84-98caaa05b32f",
            "verbose_name": null
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": true,
          "label": "Reach 3+ (%)",
          "optionName": "metric_q3dqccgnmms_kv9v2rkjsdo",
          "sqlExpression": null
        }
      ],
      "all_columns": [],
      "percent_metrics": [],
      "adhoc_filters": [
        {
          "clause": "WHERE",
          "comparator": "No filter",
          "expressionType": "SIMPLE",
          "operator": "TEMPORAL_RANGE",
          "subject": "date"
        }
      ],
      "timeseries_limit_metric": {
        "aggregate": "MIN",
        "column": {
          "advanced_data_type": null,
          "certification_details": null,
          "certified_by": null,
          "column_name": "Tuần",
          "description": null,
          "expression": null,
          "filterable": true,
          "groupby": true,
          "id": 4851,
          "is_certified": false,
          "is_dttm": false,
          "python_date_format": null,
          "type": "STRING",
          "type_generic": 1,
          "verbose_name": null,
          "warning_markdown": null
        },
        "datasourceWarning": false,
        "expressionType": "SIMPLE",
        "hasCustomLabel": false,
        "label": "MIN(Tuần)",
        "optionName": "metric_qag9nk6gnl_hx1pvh4bpdm",
        "sqlExpression": null
      },
      "order_by_cols": [],
      "row_limit": 1000,
      "server_page_length": 10,
      "order_desc": true,
      "table_timestamp_format": "smart_date",
      "allow_render_html": true,
      "column_config": {
        "Reach 1+ (%)": {
          "d3NumberFormat": ",.2f"
        },
        "Reach 2+ (%)": {
          "d3NumberFormat": ",.2f"
        },
        "Reach 3+ (%)": {
          "d3NumberFormat": ",.2f"
        },
        "Tổng user truy cập VTVgo": {
          "d3NumberFormat": ",d"
        }
      },
      "show_cell_bars": true,
      "color_pn": true,
      "comparison_color_scheme": "Green",
      "conditional_formatting": [],
      "comparison_type": "values",
      "annotation_layers": [],
      "dashboards": [
        79
      ],
      "extra_form_data": {
        "time_range": "DATEADD(DATETIME(\"today\"),-2, DAY) : DATEADD(DATETIME(\"today\"),-1, SECOND)"
      },
      "chart_id": 865,
      "label_colors": {
        "price": "#ffd04c",
        "price_usd": "#ffd04c",
        "count": "#ffd04c",
        "VTV1": "#ca2d1e",
        "VTV2": "#42932b",
        "VTV3": "#000191",
        "VTV5": "#9467bd",
        "VTV Cần Thơ": "#6ce5e8",
        "VTV4": "#8c564b",
        "VTV9": "#e377c2",
        "VTV5 Tây Nam Bộ": "#7f7f7f",
        "VTV8": "#bcbd22",
        "VTV7": "#2d8bba",
        "Thời sự - Chính luận": "#6BD3B3",
        "Phim dài tập": "#FCC550",
        "Đời sống": "#EE5960",
        "Tài liệu - Phóng sự": "#408184",
        "Giải trí": "#66CBE2",
        "Giáo dục - Đào tạo": "#5470C6",
        "Dành cho trẻ em": "#ffb2f3",
        "Thể thao": "#FF874E",
        "Sự kiện": "#03748E",
        "Quảng bá": "#8c564a",
        "Phim truyện": "#C9BBAB",
        "Quảng cáo": "#B17BAA"
      },
      "shared_label_colors": [
        "AJINOMOTO VIETN...",
        "ANGELA (WOMEN S...",
        "ANTOT THYMO",
        "ANZEN RESIDENCE...",
        "BAO KHI KHANG (...",
        "BENH VIEN DA KH...",
        "BIA HA NOI",
        "BINH VI THAI MI...",
        "BO PHE NAM HA (...",
        "BOGANIC PREMIUM...",
        "BONCHA (RTD GRE...",
        "C2 (RTD GREEN T...",
        "CASPER (AIR CON...",
        "CASTROL (MOTORB...",
        "CHANTE (WASHING...",
        "CHARMORA CITY N...",
        "CHIN-SU (CHILI ...",
        "CHIN-SU (FISH S...",
        "CHIN-SU FOODS (...",
        "CLEAR MAT LANH",
        "CLEAR MEN (MEN ...",
        "COCA-COLA (AERA...",
        "COLGATE (TOOTHP...",
        "COMFORT (FABRIC...",
        "DA HUONG (FEMIN...",
        "DONG TRUNG HA T...",
        "DOVE (HAIR CARE...",
        "DOWNY (FABRIC C...",
        "DR.THANH (RTD H...",
        "DUNG DICH XIT H...",
        "DUOC LIEU SACH ...",
        "DUOC LIEU THAI ...",
        "DUTCH LADY OMEG...",
        "Dành cho trẻ em",
        "FAMI (SOY MILK)",
        "FPT LONG CHAU P...",
        "GU NGON",
        "Giải trí",
        "HANH TRINH SUC ...",
        "HANOI (BEER)",
        "HANOI (DRAUGHT ...",
        "HAO HAO",
        "HDBANK PRIORITY",
        "HEAD & SHOULDER...",
        "HISMART",
        "HOA PHAT (TOLE)",
        "HOA PHAT STEEL ...",
        "HOAT HUYET - NH...",
        "HOAT HUYET DUON...",
        "HOAT HUYET THON...",
        "HONDA",
        "HONDA CUVE",
        "HYGIENE (FABRIC...",
        "HYUNDAI-SANTAFE...",
        "ICH NHI (COUGH ...",
        "ICH NIEU KHANG ...",
        "ICH THAN VUONG ...",
        "JEX (BONE & JOI...",
        "JUMBO VAPE (ANT...",
        "KANGAROO (WATER...",
        "KATIA PREMIUM V...",
        "KHUONG THAO DAN...",
        "KNORR (SEASONIN...",
        "KOKOMI SNACKING",
        "LIFEBUOY VITAMI...",
        "LINEABON (VITAM...",
        "LPBANK VISA",
        "MAGGI (OYSTER O...",
        "MANULIFE",
        "MB (BANK)",
        "MICHELIN",
        "MILO (ENERGY PO...",
        "MORINAGA",
        "NAGAKAWA (AIR C...",
        "NAM NGU (FISH S...",
        "NESTLE NAN",
        "NEXTG CAL (VITA...",
        "NGOC CHAU (TOOT...",
        "NGUYEN XUAN (HE...",
        "NHUOM TOC DUOC ...",
        "NUI THAN TAI MI...",
        "NUMBER 1 (ENERG...",
        "NUMBER 1 (SOY M...",
        "NUMBER 1- 0 DO ...",
        "NUOC TANG LUC 4...",
        "OMACHI (INSTANT...",
        "OMO (WASHING LI...",
        "OPTIMUM COLOS (...",
        "OPTIMUM GOLD (G...",
        "OREO (BISCUIT)",
        "P/S (TOOTHPASTE...",
        "PANADOL (COUGHS...",
        "PANTENE PRO-V (...",
        "PEPSI (AERATED ...",
        "PETRO VIETNAM (...",
        "PHU MY PETROVIE...",
        "PHUONG DONG ASA...",
        "PONNIE",
        "PURITE",
        "Phim dài tập",
        "Quảng cáo",
        "REJOICE (SHAMPO...",
        "REMOS VIET NAM",
        "ROMANO (MEN SHA...",
        "SALONPAS (PAIN ...",
        "SAM NHUNG BO TH...",
        "SENSODYNE (TOOT...",
        "SIEU THI DIEN M...",
        "STING (ENERGY D...",
        "SUBAC (ANTISEPT...",
        "SUMIKURA",
        "SUN GROUP VIETN...",
        "SUN PHUQUOC AIR...",
        "SUNLIGHT (DISH ...",
        "SUNSILK (HAIR C...",
        "SURF (WASHING L...",
        "TAM BINH (DRINK...",
        "TAY THI",
        "TECHCOMBANK",
        "TH TRUE FOOD (F...",
        "TH TRUE MILK (F...",
        "TH TRUE MISTORI",
        "TH TRUE YOGURT ...",
        "THAI DUONG (HER...",
        "THANH HANG BEAU...",
        "THE VISA SEASOU...",
        "THEP VAS",
        "TOTTRI TRAPHACO",
        "TRANG PHUC LINH...",
        "TROPICANA TWIST...",
        "TRUONG HAI AUTO...",
        "Thể thao",
        "Thời sự - Chính luận",
        "Tài liệu - Phóng sự",
        "UNIQLO (FASHION...",
        "V.ROHTO (EYE DR...",
        "VF MPV7",
        "VF8",
        "VF9",
        "VIEN NGAM THONG...",
        "VIETINBANK",
        "VIETJET AIR",
        "VIETNAM AIRLINE...",
        "VIFON MI AN LIE...",
        "VIM (WC CLEANIN...",
        "VINAMILK (EATIN...",
        "VINAMILK (FRESH...",
        "VNPT (TELECOM C...",
        "VTV1",
        "VTV2",
        "VTV3",
        "VTV8",
        "VTV9",
        "VUONG BAO (PROS...",
        "VUONG NIEU DAN ...",
        "Vui lòng chọn filter Brand",
        "YAKULT (DRINKIN...",
        "YOMOST",
        "YUMANGEL (STOMA...",
        "ZOZO IMUSE (COL...",
        "price",
        "Đời sống"
      ],
      "map_label_colors": {
        "SMART_TV": "#1FA8C9",
        "MOBILE": "#454E7C",
        "PC/Lap": "#5AC189",
        "TABLET": "#FF7F44",
        "Chưa xem hết": "#6BD3B3",
        "Xem hết": "#FCC550",
        "COUNT_DISTINCT(gr)": "#6BD3B3",
        "Vui lòng chọn filter Brand": "#FCC550",
        "COUNT_DISTINCT(prd)": "#6BD3B3",
        "KOKOMI SNACKING": "#1FA8C9",
        "MORINAGA": "#454E7C",
        "SUN GROUP VIETN...": "#5AC189",
        "HOAT HUYET - NH...": "#FF7F44",
        "BONCHA (RTD GRE...": "#666666",
        "SAM NHUNG BO TH...": "#E04355",
        "TAM BINH (DRINK...": "#FCC700",
        "MAGGI (OYSTER O...": "#A868B7",
        "STING (ENERGY D...": "#3CCCCB",
        "NESTLE NAN": "#A38F79",
        "FAMI (SOY MILK)": "#8FD3E4",
        "OMACHI (INSTANT...": "#A1A6BD",
        "C2 (RTD GREEN T...": "#ACE1C4",
        "COLGATE (TOOTHP...": "#FEC0A1",
        "DA HUONG (FEMIN...": "#B2B2B2",
        "HANOI (DRAUGHT ...": "#EFA1AA",
        "SENSODYNE (TOOT...": "#FDE380",
        "DUNG DICH XIT H...": "#D3B3DA",
        "HOA PHAT STEEL ...": "#9EE5E5",
        "AJINOMOTO VIETN...": "#D1C6BC",
        "CASTROL (MOTORB...": "#1f86c9",
        "VIFON MI AN LIE...": "#47457c",
        "BENH VIEN DA KH...": "#5ac19e",
        "BOGANIC PREMIUM...": "#ffa444",
        "TH TRUE MILK (F...": "#e05043",
        "ICH NIEU KHANG ...": "#fcf900",
        "KHUONG THAO DAN...": "#b768b6",
        "REJOICE (SHAMPO...": "#3cb0cc",
        "HOAT HUYET THON...": "#a39779",
        "THAI DUONG (HER...": "#8fc2e4",
        "TH TRUE YOGURT ...": "#a2a1bd",
        "THEP VAS": "#ace1cf",
        "HONDA": "#fed3a1",
        "PHUONG DONG ASA...": "#b2b2b2",
        "COCA-COLA (AERA...": "#efa8a1",
        "HONDA CUVE": "#fdfc80",
        "YAKULT (DRINKIN...": "#dab3d9",
        "NUMBER 1 (ENERG...": "#9ed7e5",
        "TH TRUE MISTORI": "#d1cabc",
        "YUMANGEL (STOMA...": "#1f97c9",
        "HEAD & SHOULDER...": "#1f75c9",
        "UNIQLO (FASHION...": "#4c457c",
        "DR.THANH (RTD H...": "#5ac1a8",
        "LINEABON (VITAM...": "#ffb744",
        "DOWNY (FABRIC C...": "#45497c",
        "NAM NGU (FISH S...": "#e06043",
        "REMOS VIET NAM": "#e5fc00",
        "OREO (BISCUIT)": "#b768ae",
        "THANH HANG BEAU...": "#3ca2cc",
        "HAO HAO": "#a39c79",
        "BAO KHI KHANG (...": "#8fb9e4",
        "SALONPAS (PAIN ...": "#a4a1bd",
        "VINAMILK (FRESH...": "#ace1d4",
        "GU NGON": "#fedca1",
        "VUONG BAO (PROS...": "#5ac193",
        "MILO (ENERGY PO...": "#efafa1",
        "TAY THI": "#f1fd80",
        "CHANTE (WASHING...": "#dab3d5",
        "NGUYEN XUAN (HE...": "#9ed0e5",
        "PURITE": "#d1ccbc",
        "DOVE (HAIR CARE...": "#1f64c9",
        "CLEAR MAT LANH": "#52457c",
        "SUNLIGHT (DISH ...": "#5ac1b2",
        "CHIN-SU FOODS (...": "#ffca44",
        "HOAT HUYET DUON...": "#1fa8c9",
        "P/S (TOOTHPASTE...": "#e07043",
        "TOTTRI TRAPHACO": "#ccfc00",
        "HOA PHAT (TOLE)": "#b768a6",
        "PANTENE PRO-V (...": "#3c93cc",
        "VNPT (TELECOM C...": "#a3a079",
        "VINAMILK (EATIN...": "#8fb1e4",
        "CHIN-SU (CHILI ...": "#a7a1bd",
        "PETRO VIETNAM (...": "#ace1d9",
        "DUTCH LADY OMEG...": "#fee5a1",
        "BINH VI THAI MI...": "#454e7c",
        "NGOC CHAU (TOOT...": "#efb7a1",
        "SUNSILK (HAIR C...": "#e5fd80",
        "SUMIKURA": "#dab3d1",
        "BO PHE NAM HA (...": "#9ec9e5",
        "VUONG NIEU DAN ...": "#d1cebc",
        "VF9": "#1f53c9",
        "VF8": "#57457c",
        "HDBANK PRIORITY": "#5ac1bc",
        "ROMANO (MEN SHA...": "#ffdc44",
        "ANTOT THYMO": "#1fb9c9",
        "VIETINBANK": "#e07f43",
        "TRUONG HAI AUTO...": "#b3fc00",
        "TH TRUE FOOD (F...": "#b7689e",
        "HISMART": "#3c85cc",
        "ANZEN RESIDENCE...": "#a2a379",
        "NUMBER 1 (SOY M...": "#8fa8e4",
        "KATIA PREMIUM V...": "#aaa1bd",
        "KNORR (SEASONIN...": "#ace1de",
        "TRANG PHUC LINH...": "#feeea1",
        "NUI THAN TAI MI...": "#45537c",
        "NUOC TANG LUC 4...": "#efbfa1",
        "SUBAC (ANTISEPT...": "#d8fd80",
        "NEXTG CAL (VITA...": "#dab3cd",
        "ICH THAN VUONG ...": "#9ec1e5",
        "FPT LONG CHAU P...": "#d1d0bc",
        "SUN PHUQUOC AIR...": "#5AC189",
        "KANGAROO (WATER...": "#FF7F44",
        "CHIN-SU (FISH S...": "#3CCCCB",
        "VIEN NGAM THONG...": "#EFA1AA",
        "V.ROHTO (EYE DR...": "#FDE380",
        "ZOZO IMUSE (COL...": "#1FA8C9",
        "SAM NHUNG BO THAN TW3 (ORIENTAL KIDNEY RESTORATIVE MEDICINE)": "#6BD3B3",
        "TAM BINH (DRINK SUPP.)": "#FCC550",
        "BOGANIC PREMIUM (LIVER SUPP.)": "#408184",
        "ICH NIEU KHANG (PROSTATE DISORDER SUPP.)": "#66CBE2",
        "MAGGI (OYSTER OIL)": "#EE5960",
        "BONCHA (RTD GREEN TEA)": "#484E5A",
        "ZOZO IMUSE (COLD-FLU SUPP.)": "#FF874E"
      },
      "extra_filters": [],
      "force": false,
      "result_format": "json",
      "result_type": "full"
    },
    "result_format": "json",
    "result_type": "full"
  }
};