export const allTableChartDevicePayload = {
  url: `${import.meta.env.VITE_API_DOMAIN}/api/v1/chart/data?form_data=%7B%22slice_id%22%3A830%7D&dashboard_id=54`,
  payload: {
    "datasource": {
      "id": 235,
      "type": "table"
    },
    "force": false,
    "queries": [
      {
        "time_range": "DATEADD(DATETIME(\"today\"),-2, DAY) : DATEADD(DATETIME(\"today\"),-1, SECOND)",
        "filters": [
          {
            "col": "date",
            "op": "TEMPORAL_RANGE",
            "val": "No filter"
          }
        ],
        "extras": {
          "having": "",
          "where": ""
        },
        "applied_time_extras": {},
        "columns": [
          "Tuần"
        ],
        "metrics": [
          {
            "aggregate": "SUM",
            "column": {
              "advanced_data_type": null,
              "certification_details": null,
              "certified_by": null,
              "column_name": "Tổng số spot",
              "description": null,
              "expression": null,
              "filterable": true,
              "groupby": true,
              "id": 6203,
              "is_certified": false,
              "is_dttm": false,
              "python_date_format": null,
              "type": "LONGLONG",
              "type_generic": 0,
              "verbose_name": null,
              "warning_markdown": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Tổng số spot",
            "optionName": "metric_8jy3jfndfny_1p4qpty26js",
            "sqlExpression": null
          },
          {
            "aggregate": "SUM",
            "column": {
              "advanced_data_type": null,
              "certification_details": null,
              "certified_by": null,
              "column_name": "Thời lượng (phút)",
              "description": null,
              "expression": null,
              "filterable": true,
              "groupby": true,
              "id": 6204,
              "is_certified": false,
              "is_dttm": false,
              "python_date_format": null,
              "type": "NEWDECIMAL",
              "type_generic": null,
              "verbose_name": null,
              "warning_markdown": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Thời lượng (phút)",
            "optionName": "metric_h2bs3bzsbib_zd5ldeam7bp",
            "sqlExpression": null
          },
          {
            "aggregate": "SUM",
            "column": {
              "advanced_data_type": null,
              "certification_details": null,
              "certified_by": null,
              "column_name": "Tổng số thiết bị ngày",
              "description": null,
              "expression": null,
              "filterable": true,
              "groupby": true,
              "id": 6205,
              "is_certified": false,
              "is_dttm": false,
              "python_date_format": null,
              "type": "LONGLONG",
              "type_generic": 0,
              "verbose_name": null,
              "warning_markdown": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Tổng số thiết bị",
            "optionName": "metric_futpebo0uph_9e9ng9lao37",
            "sqlExpression": null
          },
          {
            "aggregate": "AVG",
            "column": {
              "advanced_data_type": null,
              "certification_details": null,
              "certified_by": null,
              "column_name": "Reach 1+ (%)",
              "description": null,
              "expression": null,
              "filterable": true,
              "groupby": true,
              "id": 6206,
              "is_certified": false,
              "is_dttm": false,
              "python_date_format": null,
              "type": "NEWDECIMAL",
              "type_generic": null,
              "verbose_name": null,
              "warning_markdown": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Reach 1+ (%)",
            "optionName": "metric_byl21milwqg_xv3rewcikl8",
            "sqlExpression": null
          },
          {
            "aggregate": "AVG",
            "column": {
              "advanced_data_type": null,
              "certification_details": null,
              "certified_by": null,
              "column_name": "Reach 2+ (%)",
              "description": null,
              "expression": null,
              "filterable": true,
              "groupby": true,
              "id": 6207,
              "is_certified": false,
              "is_dttm": false,
              "python_date_format": null,
              "type": "NEWDECIMAL",
              "type_generic": null,
              "verbose_name": null,
              "warning_markdown": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Reach 2+ (%)",
            "optionName": "metric_pzyie0ux17k_4durgw2z0b7",
            "sqlExpression": null
          },
          {
            "aggregate": "AVG",
            "column": {
              "advanced_data_type": null,
              "certification_details": null,
              "certified_by": null,
              "column_name": "Reach 3+ (%)",
              "description": null,
              "expression": null,
              "filterable": true,
              "groupby": true,
              "id": 6208,
              "is_certified": false,
              "is_dttm": false,
              "python_date_format": null,
              "type": "NEWDECIMAL",
              "type_generic": null,
              "verbose_name": null,
              "warning_markdown": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Reach 3+ (%)",
            "optionName": "metric_lq6hs8uswcp_0hmn6n1daozi",
            "sqlExpression": null
          }
        ],
        "orderby": [
          [
            {
              "aggregate": "SUM",
              "column": {
                "advanced_data_type": null,
                "certification_details": null,
                "certified_by": null,
                "column_name": "Tổng số spot",
                "description": null,
                "expression": null,
                "filterable": true,
                "groupby": true,
                "id": 6203,
                "is_certified": false,
                "is_dttm": false,
                "python_date_format": null,
                "type": "LONGLONG",
                "type_generic": 0,
                "verbose_name": null,
                "warning_markdown": null
              },
              "datasourceWarning": false,
              "expressionType": "SIMPLE",
              "hasCustomLabel": true,
              "label": "Tổng số spot",
              "optionName": "metric_8jy3jfndfny_1p4qpty26js",
              "sqlExpression": null
            },
            false
          ]
        ],
        "annotation_layers": [],
        "row_limit": 50000,
        "series_limit": 0,
        "order_desc": false,
        "url_params": {},
        "custom_params": {},
        "custom_form_data": {},
        "post_processing": [],
        "time_offsets": []
      }
    ],
    "form_data": {
      "datasource": "235__table",
      "viz_type": "table",
      "slice_id": 830,
      "url_params": {},
      "query_mode": "aggregate",
      "groupby": [
        "Tuần"
      ],
      "temporal_columns_lookup": {
        "date": true
      },
      "metrics": [
        {
          "aggregate": "SUM",
          "column": {
            "advanced_data_type": null,
            "certification_details": null,
            "certified_by": null,
            "column_name": "Tổng số spot",
            "description": null,
            "expression": null,
            "filterable": true,
            "groupby": true,
            "id": 6203,
            "is_certified": false,
            "is_dttm": false,
            "python_date_format": null,
            "type": "LONGLONG",
            "type_generic": 0,
            "verbose_name": null,
            "warning_markdown": null
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": true,
          "label": "Tổng số spot",
          "optionName": "metric_8jy3jfndfny_1p4qpty26js",
          "sqlExpression": null
        },
        {
          "aggregate": "SUM",
          "column": {
            "advanced_data_type": null,
            "certification_details": null,
            "certified_by": null,
            "column_name": "Thời lượng (phút)",
            "description": null,
            "expression": null,
            "filterable": true,
            "groupby": true,
            "id": 6204,
            "is_certified": false,
            "is_dttm": false,
            "python_date_format": null,
            "type": "NEWDECIMAL",
            "type_generic": null,
            "verbose_name": null,
            "warning_markdown": null
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": true,
          "label": "Thời lượng (phút)",
          "optionName": "metric_h2bs3bzsbib_zd5ldeam7bp",
          "sqlExpression": null
        },
        {
          "aggregate": "SUM",
          "column": {
            "advanced_data_type": null,
            "certification_details": null,
            "certified_by": null,
            "column_name": "Tổng số thiết bị ngày",
            "description": null,
            "expression": null,
            "filterable": true,
            "groupby": true,
            "id": 6205,
            "is_certified": false,
            "is_dttm": false,
            "python_date_format": null,
            "type": "LONGLONG",
            "type_generic": 0,
            "verbose_name": null,
            "warning_markdown": null
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": true,
          "label": "Tổng số thiết bị",
          "optionName": "metric_futpebo0uph_9e9ng9lao37",
          "sqlExpression": null
        },
        {
          "aggregate": "AVG",
          "column": {
            "advanced_data_type": null,
            "certification_details": null,
            "certified_by": null,
            "column_name": "Reach 1+ (%)",
            "description": null,
            "expression": null,
            "filterable": true,
            "groupby": true,
            "id": 6206,
            "is_certified": false,
            "is_dttm": false,
            "python_date_format": null,
            "type": "NEWDECIMAL",
            "type_generic": null,
            "verbose_name": null,
            "warning_markdown": null
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": true,
          "label": "Reach 1+ (%)",
          "optionName": "metric_byl21milwqg_xv3rewcikl8",
          "sqlExpression": null
        },
        {
          "aggregate": "AVG",
          "column": {
            "advanced_data_type": null,
            "certification_details": null,
            "certified_by": null,
            "column_name": "Reach 2+ (%)",
            "description": null,
            "expression": null,
            "filterable": true,
            "groupby": true,
            "id": 6207,
            "is_certified": false,
            "is_dttm": false,
            "python_date_format": null,
            "type": "NEWDECIMAL",
            "type_generic": null,
            "verbose_name": null,
            "warning_markdown": null
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": true,
          "label": "Reach 2+ (%)",
          "optionName": "metric_pzyie0ux17k_4durgw2z0b7",
          "sqlExpression": null
        },
        {
          "aggregate": "AVG",
          "column": {
            "advanced_data_type": null,
            "certification_details": null,
            "certified_by": null,
            "column_name": "Reach 3+ (%)",
            "description": null,
            "expression": null,
            "filterable": true,
            "groupby": true,
            "id": 6208,
            "is_certified": false,
            "is_dttm": false,
            "python_date_format": null,
            "type": "NEWDECIMAL",
            "type_generic": null,
            "verbose_name": null,
            "warning_markdown": null
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": true,
          "label": "Reach 3+ (%)",
          "optionName": "metric_lq6hs8uswcp_0hmn6n1daozi",
          "sqlExpression": null
        }
      ],
      "all_columns": [],
      "percent_metrics": [],
      "adhoc_filters": [
        {
          "clause": "WHERE",
          "comparator": "No filter",
          "expressionType": "SIMPLE",
          "operator": "TEMPORAL_RANGE",
          "subject": "date"
        }
      ],
      "order_by_cols": [],
      "row_limit": 50000,
      "server_page_length": 10,
      "order_desc": false,
      "table_timestamp_format": "smart_date",
      "include_search": true,
      "allow_render_html": true,
      "column_config": {
        "Tổng số thiết bị": {
          "d3NumberFormat": ",d"
        }
      },
      "show_cell_bars": true,
      "color_pn": true,
      "comparison_color_scheme": "Green",
      "conditional_formatting": [],
      "comparison_type": "values",
      "annotation_layers": [],
      "dashboards": [
        93
      ],
      "extra_form_data": {
        "time_range": "DATEADD(DATETIME(\"today\"),-2, DAY) : DATEADD(DATETIME(\"today\"),-1, SECOND)"
      },
      "chart_id": 830,
      "label_colors": {
        "price": "#ffd04c",
        "price_usd": "#ffd04c",
        "count": "#ffd04c",
        "VTV1": "#ca2d1e",
        "VTV2": "#42932b",
        "VTV3": "#000191",
        "VTV5": "#9467bd",
        "VTV Cần Thơ": "#6ce5e8",
        "VTV4": "#8c564b",
        "VTV9": "#e377c2",
        "VTV5 Tây Nam Bộ": "#7f7f7f",
        "VTV8": "#bcbd22",
        "VTV7": "#2d8bba",
        "Thời sự - Chính luận": "#6BD3B3",
        "Phim dài tập": "#FCC550",
        "Đời sống": "#EE5960",
        "Tài liệu - Phóng sự": "#408184",
        "Giải trí": "#66CBE2",
        "Giáo dục - Đào tạo": "#5470C6",
        "Dành cho trẻ em": "#ffb2f3",
        "Thể thao": "#FF874E",
        "Sự kiện": "#03748E",
        "Quảng bá": "#8c564a",
        "Phim truyện": "#C9BBAB",
        "Quảng cáo": "#B17BAA"
      },
      "shared_label_colors": [
        "AJINOMOTO VIETN...",
        "ALIPAS (MEN SUP...",
        "ANTOT THYMO",
        "BAO KHI KHANG (...",
        "BAO THANH (COUG...",
        "BENH VIEN DA KH...",
        "BINH VI THAI MI...",
        "BO PHE NAM HA (...",
        "BOGANIC PREMIUM...",
        "BONCHA (RTD GRE...",
        "C2 (RTD GREEN T...",
        "CASTROL (MOTORB...",
        "CHANTE (WASHING...",
        "CHIN-SU (CHILI ...",
        "CHIN-SU (FISH S...",
        "CLEAR MAT LANH",
        "CLEAR MEN (MEN ...",
        "COCA-COLA (AERA...",
        "COLGATE (TOOTHP...",
        "DA HUONG (FEMIN...",
        "DOVE (HAIR CARE...",
        "DOWNY (FABRIC C...",
        "DR.THANH (RTD H...",
        "DUNG DICH XIT H...",
        "DUTCH LADY OMEG...",
        "Dành cho trẻ em",
        "ENTEROGERMINA (...",
        "FAMI (SOY MILK)",
        "GU NGON",
        "Giáo dục - Đào tạo",
        "Giải trí",
        "HANOI (DRAUGHT ...",
        "HAO HAO",
        "HDBANK PRIORITY",
        "HEAD & SHOULDER...",
        "HISMART",
        "HOA PHAT (TOLE)",
        "HOA PHAT STEEL ...",
        "HOAT HUYET - NH...",
        "HOAT HUYET DUON...",
        "HOAT HUYET THON...",
        "HONDA",
        "HONDA CUVE",
        "ICH NIEU KHANG ...",
        "IMPERIA HOLIDAY...",
        "INTIMATE",
        "KANGAROO (WATER...",
        "KHUONG THAO DAN...",
        "KNORR (SEASONIN...",
        "KOKOMI SNACKING",
        "LIFEBUOY VITAMI...",
        "LINEABON (VITAM...",
        "MAGGI (OYSTER O...",
        "MILO (ENERGY PO...",
        "MORINAGA",
        "NAM NGU (FISH S...",
        "NESTLE NAN",
        "NEXTG CAL (VITA...",
        "NGOC CHAU (TOOT...",
        "NGUYEN XUAN (HE...",
        "NUMBER 1 (ENERG...",
        "NUMBER 1- 0 DO ...",
        "NUOC TANG LUC 4...",
        "OMACHI (INSTANT...",
        "OPTIMUM COLOS (...",
        "OREO (BISCUIT)",
        "P/S (TOOTHPASTE...",
        "PETRO VIETNAM (...",
        "PHUONG DONG ASA...",
        "PROSPAN (COUGH ...",
        "PSA",
        "PURITE",
        "Phim dài tập",
        "Quảng cáo",
        "REJOICE (SHAMPO...",
        "REMOS VIET NAM",
        "ROMANO (MEN SHA...",
        "SALONPAS (PAIN ...",
        "SAM NHUNG BO TH...",
        "SENSODYNE (TOOT...",
        "STING (ENERGY D...",
        "SUBAC (ANTISEPT...",
        "SUN GROUP VIETN...",
        "SUN PHUQUOC AIR...",
        "SUNLIGHT (DISH ...",
        "SUNSILK (HAIR C...",
        "TAM BINH (DRINK...",
        "TAY THI",
        "TH TRUE FOOD (F...",
        "TH TRUE MILK (F...",
        "TH TRUE MISTORI",
        "TH TRUE YOGURT ...",
        "THAI DUONG (HER...",
        "THANH HANG BEAU...",
        "TRANG PHUC LINH...",
        "TRUONG HAI AUTO...",
        "Thể thao",
        "Thời sự - Chính luận",
        "Tài liệu - Phóng sự",
        "UNIQLO (FASHION...",
        "VF8",
        "VF9",
        "VIEN NGAM THONG...",
        "VIFON MI AN LIE...",
        "VIM (WC CLEANIN...",
        "VINAMILK (EATIN...",
        "VINAMILK (FRESH...",
        "VTV1",
        "VTV2",
        "VTV3",
        "VTV8",
        "VTV9",
        "VUONG BAO (PROS...",
        "VUONG NIEU DAN ...",
        "Vui lòng chọn filter Brand",
        "WIT (EYE SUPP.)",
        "YAKULT (DRINKIN...",
        "YUMANGEL (STOMA...",
        "price",
        "Đời sống"
      ],
      "map_label_colors": {},
      "extra_filters": [],
      "force": false,
      "result_format": "json",
      "result_type": "full"
    },
    "result_format": "json",
    "result_type": "full"
  }
};