export const maxInsertPayload = {
  url: `${import.meta.env.VITE_API_DOMAIN}/api/v1/chart/data?form_data=%7B%22slice_id%22%3A750%7D&dashboard_id=50`,
  payload: {
    "datasource": {
        "id": 221,
        "type": "table"
    },
    "force": false,
    "queries": [
        {
            "filters": [
                {
                    "col": "table_name",
                    "op": "==",
                    "val": "data_dashboard_spot"
                }
            ],
            "extras": {
                "having": "",
                "where": ""
            },
            "applied_time_extras": {},
            "columns": [],
            "metrics": [
                {
                    "aggregate": "MAX",
                    "column": {
                        "advanced_data_type": null,
                        "changed_on": "2026-04-04T05:07:20.342450",
                        "column_name": "check_time",
                        "created_on": "2026-04-04T05:07:20.342446",
                        "description": null,
                        "expression": null,
                        "extra": null,
                        "filterable": true,
                        "groupby": true,
                        "id": 2811,
                        "is_active": true,
                        "is_dttm": false,
                        "python_date_format": null,
                        "type": "DATETIME",
                        "type_generic": 1,
                        "uuid": "005d251e-323b-4db2-926f-2b0668ec9001",
                        "verbose_name": null
                    },
                    "datasourceWarning": false,
                    "expressionType": "SIMPLE",
                    "hasCustomLabel": false,
                    "label": "MAX(check_time)",
                    "optionName": "metric_2ds0eotid2t_duvzvxwe3te",
                    "sqlExpression": null
                }
            ],
            "annotation_layers": [],
            "series_limit": 0,
            "order_desc": true,
            "url_params": {
                "native_filters_key": "kcUkJRgRNHg2GGWZBVRWX_tbHnZhIGoe8fSi1uGsex8PKP4uVV1KxpmQq1yazkhU"
            },
            "custom_params": {},
            "custom_form_data": {}
        }
    ],
    "form_data": {
        "datasource": "221__table",
        "viz_type": "big_number_total",
        "slice_id": 750,
        "url_params": {
            "native_filters_key": "kcUkJRgRNHg2GGWZBVRWX_tbHnZhIGoe8fSi1uGsex8PKP4uVV1KxpmQq1yazkhU"
        },
        "metric": {
            "aggregate": "MAX",
            "column": {
                "advanced_data_type": null,
                "changed_on": "2026-04-04T05:07:20.342450",
                "column_name": "check_time",
                "created_on": "2026-04-04T05:07:20.342446",
                "description": null,
                "expression": null,
                "extra": null,
                "filterable": true,
                "groupby": true,
                "id": 2811,
                "is_active": true,
                "is_dttm": false,
                "python_date_format": null,
                "type": "DATETIME",
                "type_generic": 1,
                "uuid": "005d251e-323b-4db2-926f-2b0668ec9001",
                "verbose_name": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": false,
            "label": "MAX(check_time)",
            "optionName": "metric_2ds0eotid2t_duvzvxwe3te",
            "sqlExpression": null
        },
        "adhoc_filters": [
            {
                "clause": "WHERE",
                "comparator": "data_dashboard_spot",
                "datasourceWarning": false,
                "expressionType": "SIMPLE",
                "filterOptionName": "filter_fh5e11z6bvp_lx182bqqvp",
                "isExtra": false,
                "isNew": false,
                "operator": "==",
                "operatorId": "EQUALS",
                "sqlExpression": null,
                "subject": "table_name"
            }
        ],
        "header_font_size": 0.4,
        "subheader_font_size": 0.15,
        "y_axis_format": "SMART_NUMBER",
        "time_format": "%d/%m/%Y %H:%M",
        "conditional_formatting": [],
        "dashboards": [
            52
        ],
        "extra_form_data": {},
        "chart_id": 750,
        "label_colors": {
            "price": "#ffd04c",
            "price_usd": "#ffd04c",
            "count": "#ffd04c",
            "VTV1": "#ca2d1e",
            "VTV2": "#42932b",
            "VTV3": "#000191",
            "VTV5": "#9467bd",
            "VTV Cần Thơ": "#6ce5e8",
            "VTV4": "#8c564b",
            "VTV9": "#e377c2",
            "VTV5 Tây Nam Bộ": "#7f7f7f",
            "VTV8": "#bcbd22",
            "VTV7": "#2d8bba",
            "Thời sự - Chính luận": "#6BD3B3",
            "Phim dài tập": "#FCC550",
            "Đời sống": "#EE5960",
            "Tài liệu - Phóng sự": "#408184",
            "Giải trí": "#66CBE2",
            "Giáo dục - Đào tạo": "#5470C6",
            "Dành cho trẻ em": "#ffb2f3",
            "Thể thao": "#FF874E",
            "Sự kiện": "#03748E",
            "Quảng bá": "#8c564a",
            "Phim truyện": "#C9BBAB",
            "Quảng cáo": "#B17BAA"
        },
        "shared_label_colors": [
            "1.Sáng (0h - 11h)",
            "2.Trưa (11h - 14h)",
            "3.Chiều (14h - 18h)",
            "4.Tối (18h - 24h)",
            "ANTOT THYMO",
            "BINH DIEN FERTI...",
            "CASPER (AIR CONDITIONER)",
            "CASPER ELECTRIC...",
            "CASTROL BP PETC...",
            "CHIN-SU (CHILI SAUCE)",
            "COLGATE (TOOTHPASTE)",
            "CONG TY CO PHAN...",
            "CONG TY CP TAP ...",
            "CONG TY SINO VI...",
            "CONG TY TNHH BE...",
            "CONG TY TNHH CH...",
            "CONG TY TNHH DU...",
            "DAI BAC CO., LT...",
            "DAT VIET CERAMI...",
            "DHC GROUP",
            "DONG LUC GROUP",
            "Dành cho trẻ em",
            "ECO PHARMACY JS...",
            "FUMAKILLA VIETN...",
            "GLAXO SMITHKLIN...",
            "Giáo dục - Đào tạo",
            "Giải trí",
            "HANOI BEVERAGE ...",
            "HCMC HOUSING DE...",
            "HOA PHAT (TOLE)",
            "HOA PHAT STEEL ...",
            "HOAT HUYET DUONG NAO-TRAPHACO (TRAD. BRAIN HEALTH MED.)",
            "HYUNDAI THANH C...",
            "ICH NIEU KHANG (PROSTATE DISORDER SUPP.)",
            "JUMBO VAPE (ANTI-MOSQUITO COIL & SPRAY)",
            "KANGAROO (WATER FILTER)",
            "KANGAROO GROUP",
            "KOKOMI SNACKING",
            "LONG HAI CO., L...",
            "MANULIFE",
            "MASAN CONSUMER ...",
            "MICHELIN",
            "NAM NGU (FISH SAUCE)",
            "NGAN HANG THUON...",
            "NGAN HANG TMCP ...",
            "NHAT NHAT TRADI...",
            "P&G VIETNAM CO....",
            "PANTENE PRO-V (SHAMPOO & CONDITIONER)",
            "PETROVIETNAM",
            "PONNIE",
            "Phim dài tập",
            "Quảng bá",
            "Quảng cáo",
            "SAIGON CO.OP (S...",
            "SAIGON TOURIST ...",
            "SAM NHUNG BO THAN TW3 (ORIENTAL KIDNEY RESTORATIVE MEDICINE)",
            "SUN GROUP CORPO...",
            "SUN GROUP VIETNAM (REAL ESTATE COMPANY)",
            "TAM BINH (DRINK SUPP.)",
            "TAM BINH PHARMA...",
            "TAN HIEP PHAT B...",
            "TH MILK FOOD JS...",
            "TH TRUE MILK (FRESH MILK)",
            "THAM MY VIEN KA...",
            "TRAPHACO JSC",
            "TRUONG HAI AUTO CO., LTD",
            "TRUONG HAI AUTO...",
            "TRUONG HAI GROU...",
            "Thể thao",
            "Thời sự - Chính luận",
            "Tài liệu - Phóng sự",
            "UNILEVER VIETNA...",
            "VAS GROUP",
            "VIETNAM NATIONA...",
            "VIETNAM POST & ...",
            "VINACAFE (COFFEE CORPORATE)",
            "VINAMILK (FRESH MILK)",
            "VINAMILK CORPOR...",
            "VTV1",
            "VTV10",
            "VTV2",
            "VTV3",
            "VTV4",
            "VTV7",
            "VTV8",
            "VTV9",
            "XANH ISLAND CAT BA (LEISURE PROPERTY)",
            "YAKULT VIETNAM ...",
            "ZOZO IMUSE (COLD-FLU SUPP.)",
            "price",
            "price_usd",
            "Đời sống"
        ],
        "map_label_colors": {},
        "extra_filters": [],
        "force": false,
        "result_format": "json",
        "result_type": "full"
    },
    "result_format": "json",
    "result_type": "full"
  }
};