export const percentBartChartPlatformViewPayload = {
  url: `${import.meta.env.VITE_API_DOMAIN}/api/v1/chart/data?form_data=%7B%22slice_id%22%3A841%7D&dashboard_id=54`,
  payload: {
    "datasource": {
      "id": 225,
      "type": "table"
    },
    "force": false,
    "queries": [
      {
        "time_range": "DATEADD(DATETIME(\"today\"),-2, DAY) : DATEADD(DATETIME(\"today\"),-1, SECOND)",
        "filters": [
          {
            "col": "date",
            "op": "TEMPORAL_RANGE",
            "val": "No filter"
          }
        ],
        "extras": {
          "having": "",
          "where": ""
        },
        "applied_time_extras": {},
        "columns": [
          {
            "columnType": "BASE_AXIS",
            "sqlExpression": "platform",
            "label": "platform",
            "expressionType": "SQL"
          }
        ],
        "metrics": [
          {
            "aggregate": null,
            "column": null,
            "datasourceWarning": false,
            "expressionType": "SQL",
            "hasCustomLabel": true,
            "label": "Chưa xem hết",
            "optionName": "metric_gcv2d5s8qqb_l6ca6new78",
            "sqlExpression": "1-avg(duration_view/(round(duration,0)*user_view_spot))"
          },
          {
            "aggregate": null,
            "column": null,
            "datasourceWarning": false,
            "expressionType": "SQL",
            "hasCustomLabel": true,
            "label": "Xem hết",
            "optionName": "metric_paz48ttdmm_b93kyfla4h6",
            "sqlExpression": "avg(duration_view/(round(duration,0)*user_view_spot))"
          }
        ],
        "orderby": [
          [
            {
              "aggregate": null,
              "column": null,
              "datasourceWarning": false,
              "expressionType": "SQL",
              "hasCustomLabel": true,
              "label": "Chưa xem hết",
              "optionName": "metric_gcv2d5s8qqb_l6ca6new78",
              "sqlExpression": "1-avg(duration_view/(round(duration,0)*user_view_spot))"
            },
            false
          ]
        ],
        "annotation_layers": [],
        "row_limit": 100,
        "series_columns": [],
        "series_limit": 0,
        "order_desc": true,
        "url_params": {},
        "custom_params": {},
        "custom_form_data": {},
        "time_offsets": [],
        "post_processing": [
          {
            "operation": "pivot",
            "options": {
              "index": [
                "platform"
              ],
              "columns": [],
              "aggregates": {
                "Chưa xem hết": {
                  "operator": "mean"
                },
                "Xem hết": {
                  "operator": "mean"
                }
              },
              "drop_missing_columns": false
            }
          },
          {
            "operation": "contribution",
            "options": {
              "orientation": "row",
              "time_shifts": []
            }
          },
          {
            "operation": "flatten"
          }
        ]
      }
    ],
    "form_data": {
      "datasource": "225__table",
      "viz_type": "echarts_timeseries_bar",
      "slice_id": 841,
      "url_params": {},
      "x_axis": "platform",
      "x_axis_sort_asc": true,
      "x_axis_sort_series": "name",
      "x_axis_sort_series_ascending": true,
      "metrics": [
        {
          "aggregate": null,
          "column": null,
          "datasourceWarning": false,
          "expressionType": "SQL",
          "hasCustomLabel": true,
          "label": "Chưa xem hết",
          "optionName": "metric_gcv2d5s8qqb_l6ca6new78",
          "sqlExpression": "1-avg(duration_view/(round(duration,0)*user_view_spot))"
        },
        {
          "aggregate": null,
          "column": null,
          "datasourceWarning": false,
          "expressionType": "SQL",
          "hasCustomLabel": true,
          "label": "Xem hết",
          "optionName": "metric_paz48ttdmm_b93kyfla4h6",
          "sqlExpression": "avg(duration_view/(round(duration,0)*user_view_spot))"
        }
      ],
      "groupby": [],
      "contributionMode": "row",
      "adhoc_filters": [
        {
          "clause": "WHERE",
          "comparator": "No filter",
          "expressionType": "SIMPLE",
          "operator": "TEMPORAL_RANGE",
          "subject": "date"
        }
      ],
      "order_desc": true,
      "row_limit": 100,
      "truncate_metric": true,
      "show_empty_columns": true,
      "comparison_type": "values",
      "annotation_layers": [],
      "forecastPeriods": 10,
      "forecastInterval": 0.8,
      "orientation": "vertical",
      "x_axis_title_margin": 15,
      "y_axis_title_margin": 15,
      "y_axis_title_position": "Left",
      "sort_series_type": "max",
      "sort_series_ascending": true,
      "color_scheme": "presetColors",
      "time_shift_color": true,
      "show_value": true,
      "stack": "Stack",
      "only_total": false,
      "percentage_threshold": 0,
      "minorTicks": false,
      "zoomable": false,
      "show_legend": true,
      "legendType": "scroll",
      "legendOrientation": "top",
      "legendMargin": null,
      "x_axis_time_format": "smart_date",
      "y_axis_format": "SMART_NUMBER",
      "logAxis": false,
      "y_axis_bounds": [
        null,
        null
      ],
      "truncateXAxis": true,
      "rich_tooltip": true,
      "showTooltipTotal": true,
      "showTooltipPercentage": true,
      "tooltipTimeFormat": "smart_date",
      "dashboards": [
        54
      ],
      "extra_form_data": {
        "time_range": "DATEADD(DATETIME(\"today\"),-2, DAY) : DATEADD(DATETIME(\"today\"),-1, SECOND)"
      },
      "chart_id": 841,
      "label_colors": {
        "price": "#ffd04c",
        "price_usd": "#ffd04c",
        "count": "#ffd04c",
        "VTV1": "#ca2d1e",
        "VTV2": "#42932b",
        "VTV3": "#000191",
        "VTV5": "#9467bd",
        "VTV Cần Thơ": "#6ce5e8",
        "VTV4": "#8c564b",
        "VTV9": "#e377c2",
        "VTV5 Tây Nam Bộ": "#7f7f7f",
        "VTV8": "#bcbd22",
        "VTV7": "#2d8bba",
        "Thời sự - Chính luận": "#6BD3B3",
        "Phim dài tập": "#FCC550",
        "Đời sống": "#EE5960",
        "Tài liệu - Phóng sự": "#408184",
        "Giải trí": "#66CBE2",
        "Giáo dục - Đào tạo": "#5470C6",
        "Dành cho trẻ em": "#ffb2f3",
        "Thể thao": "#FF874E",
        "Sự kiện": "#03748E",
        "Quảng bá": "#8c564a",
        "Phim truyện": "#C9BBAB",
        "Quảng cáo": "#B17BAA"
      },
      "shared_label_colors": [
        "AJINOMOTO VIETN...",
        "ALIPAS (MEN SUP...",
        "ANTOT THYMO",
        "BAO KHI KHANG (...",
        "BAO THANH (COUG...",
        "BENH VIEN DA KH...",
        "BIA HA NOI",
        "BINH VI THAI MI...",
        "BO PHE NAM HA (...",
        "BO PHE NHAT NHA...",
        "BOGANIC PREMIUM...",
        "BONCHA (RTD GRE...",
        "BONI BRAIN (ANT...",
        "C2 (RTD GREEN T...",
        "CASPER (AIR CON...",
        "CASTROL (MOTORB...",
        "CENLAND",
        "CENTA RIVERSIDE",
        "CHANTE (WASHING...",
        "CHARMORA CITY N...",
        "CHIN-SU (CHILI ...",
        "CHIN-SU (FISH S...",
        "CLEAR MAT LANH",
        "CLEAR MEN (MEN ...",
        "COCA-COLA (AERA...",
        "COLGATE (TOOTHP...",
        "COMFORT (FABRIC...",
        "DA HUONG (FEMIN...",
        "DAT VIET CERAMI...",
        "DONG LUC TOWER",
        "DONG TRUNG HA T...",
        "DOVE (HAIR CARE...",
        "DOWNY (FABRIC C...",
        "DR.THANH (RTD H...",
        "DUNG DICH XIT H...",
        "DUTCH LADY OMEG...",
        "Dành cho trẻ em",
        "ENCHANTEUR (SHO...",
        "ENSURE (NUTRITI...",
        "ENTEROGERMINA (...",
        "FAMI (SOY MILK)",
        "FLC PREMIER PAR...",
        "FPT LONG CHAU P...",
        "GU NGON",
        "Giáo dục - Đào tạo",
        "Giải trí",
        "HANOI (BEER)",
        "HANOI (DRAUGHT ...",
        "HAO HAO",
        "HD BANK",
        "HDBANK PRIORITY",
        "HEAD & SHOULDER...",
        "HISMART",
        "HOA PHAT (TOLE)",
        "HOA PHAT STEEL ...",
        "HOAT HUYET - NH...",
        "HOAT HUYET DUON...",
        "HOAT HUYET THON...",
        "HONDA",
        "HONDA CUVE",
        "HONG SAM THAI M...",
        "HONG SAM VIET N...",
        "HYUNDAI-SANTAFE...",
        "ICH NIEU KHANG ...",
        "IMPERIA HOLIDAY...",
        "INTIMATE",
        "JEX (BONE & JOI...",
        "JOGARBOLA",
        "JUMBO VAPE (ANT...",
        "KANGAROO (WATER...",
        "KATIA PREMIUM V...",
        "KHUONG THAO DAN...",
        "KINGSUP (MEN SU...",
        "KNORR (SEASONIN...",
        "KOKOMI SNACKING",
        "LIFEBUOY VITAMI...",
        "LINEABON (VITAM...",
        "LOCPHAT PAY",
        "LPBANK",
        "LPBANK VISA",
        "LYNNTIMES ONSEN...",
        "MAGGI (OYSTER O...",
        "MANULIFE",
        "MB (BANK)",
        "MICHELIN",
        "MILO (ENERGY PO...",
        "MOLFIX OXY",
        "MORINAGA",
        "NAGAKAWA (AIR C...",
        "NAM NGU (FISH S...",
        "NESTLE NAN",
        "NEXTG CAL (VITA...",
        "NGOC CHAU (TOOT...",
        "NGUYEN XUAN (HE...",
        "NOBLE PALACE TA...",
        "NUI THAN TAI MI...",
        "NUMBER 1 (ENERG...",
        "NUMBER 1 (SOY M...",
        "NUMBER 1- 0 DO ...",
        "NUOC TANG LUC 4...",
        "OMACHI (INSTANT...",
        "OMO (WASHING LI...",
        "OPTIMUM COLOS (...",
        "OREO (BISCUIT)",
        "OTIV (BRAIN SUP...",
        "P/S (TOOTHPASTE...",
        "PANTENE PRO-V (...",
        "PEPSI (AERATED ...",
        "PETRO VIETNAM (...",
        "PHU MY PETROVIE...",
        "PHUONG DONG ASA...",
        "PLUSSSZ",
        "PONNIE",
        "POWER OF SUN",
        "PROSPAN (COUGH ...",
        "PSA",
        "PURITE",
        "PV GAS - PETROV...",
        "Phim dài tập",
        "Quảng cáo",
        "RED BULL (ENERG...",
        "REJOICE (SHAMPO...",
        "REMOS VIET NAM",
        "ROMA D-MAXX MAR...",
        "ROMANO (MEN SHA...",
        "SAIGON TOURIST ...",
        "SALONPAS (PAIN ...",
        "SAM NHUNG BO TH...",
        "SCTV CHANNELS (...",
        "SENSODYNE (TOOT...",
        "SIEU THI DIEN M...",
        "SINO VANLOCK EL...",
        "STING (ENERGY D...",
        "SUBAC (ANTISEPT...",
        "SUMIKURA",
        "SUN GROUP VIETN...",
        "SUN PHUQUOC AIR...",
        "SUNLIGHT (DISH ...",
        "SUNSILK (HAIR C...",
        "SURF (WASHING L...",
        "TAM BINH (DRINK...",
        "TAY THI",
        "TH TRUE FOOD (F...",
        "TH TRUE MILK (F...",
        "TH TRUE MISTORI",
        "TH TRUE YOGURT ...",
        "THAI DUONG (HER...",
        "THANH HANG BEAU...",
        "THEP VAS",
        "TRANG PHUC LINH...",
        "TROPICANA TWIST...",
        "TRUONG HAI AUTO...",
        "Thể thao",
        "Thời sự - Chính luận",
        "Tài liệu - Phóng sự",
        "UNIQLO (FASHION...",
        "VF8",
        "VF9",
        "VIEN NGAM THONG...",
        "VIFON MI AN LIE...",
        "VIM (WC CLEANIN...",
        "VINACAFE (COFFE...",
        "VINAGA - DHA",
        "VINAMILK (EATIN...",
        "VINAMILK (FRESH...",
        "VTV1",
        "VTV2",
        "VTV3",
        "VTV8",
        "VTV9",
        "VUONG BAO (PROS...",
        "VUONG NIEU DAN ...",
        "Vui lòng chọn filter Brand",
        "WIT (EYE SUPP.)",
        "XANH ISLAND CAT...",
        "YAKULT (DRINKIN...",
        "YOMOST",
        "YOOSUN (FACIAL ...",
        "YUMANGEL (STOMA...",
        "ZOZO IMUSE (COL...",
        "price",
        "Đời sống"
      ],
      "map_label_colors": {},
      "own_color_scheme": "presetColors",
      "extra_filters": [],
      "force": false,
      "result_format": "json",
      "result_type": "full"
    },
    "result_format": "json",
    "result_type": "full"
  }
};