export const reachBarChartChannelPayload = {
    url: `${import.meta.env.VITE_API_DOMAIN}/api/v1/chart/data?form_data=%7B%22slice_id%22%3A926%7D&dashboard_id=54`,
    payload: {
        "datasource": {
            "id": 283,
            "type": "table"
        },
        "force": false,
        "queries": [
            {
                "time_range": "DATEADD(DATETIME(\"today\"),-2, DAY) : DATEADD(DATETIME(\"today\"),-1, SECOND)",
                "filters": [
                    {
                        "col": "date",
                        "op": "TEMPORAL_RANGE",
                        "val": "No filter"
                    }
                ],
                "extras": {
                    "time_grain_sqla": "P1D",
                    "having": "",
                    "where": ""
                },
                "applied_time_extras": {},
                "columns": [
                    {
                        "timeGrain": "P1D",
                        "columnType": "BASE_AXIS",
                        "datasourceWarning": false,
                        "expressionType": "SQL",
                        "label": "brand",
                        "sqlExpression": "CASE\r\nWHEN length(brand) > 15\r\n   THEN CONCAT(left(brand, 15), '...')\r\nELSE brand\r\nEND"
                    },
                    "channel_name_tvd"
                ],
                "metrics": [
                    {
                        "aggregate": "SUM",
                        "column": {
                            "advanced_data_type": null,
                            "changed_on": "2026-01-08T03:03:57.316123",
                            "column_name": "reach",
                            "created_on": "2026-01-08T03:03:57.316115",
                            "description": null,
                            "expression": null,
                            "extra": "{}",
                            "filterable": true,
                            "groupby": true,
                            "id": 5328,
                            "is_active": true,
                            "is_dttm": false,
                            "python_date_format": null,
                            "type": "LONGLONG",
                            "type_generic": 0,
                            "uuid": "57d3108e-a0b9-402b-abe0-3ed65e21c9d2",
                            "verbose_name": null
                        },
                        "datasourceWarning": false,
                        "expressionType": "SIMPLE",
                        "hasCustomLabel": false,
                        "label": "SUM(reach)",
                        "optionName": "metric_y2ea5imb0n_ifyzgnajnfd",
                        "sqlExpression": null
                    }
                ],
                "orderby": [
                    [
                        {
                            "aggregate": "SUM",
                            "column": {
                                "advanced_data_type": null,
                                "changed_on": "2026-01-08T03:03:57.316123",
                                "column_name": "reach",
                                "created_on": "2026-01-08T03:03:57.316115",
                                "description": null,
                                "expression": null,
                                "extra": "{}",
                                "filterable": true,
                                "groupby": true,
                                "id": 5328,
                                "is_active": true,
                                "is_dttm": false,
                                "python_date_format": null,
                                "type": "LONGLONG",
                                "type_generic": 0,
                                "uuid": "57d3108e-a0b9-402b-abe0-3ed65e21c9d2",
                                "verbose_name": null
                            },
                            "datasourceWarning": false,
                            "expressionType": "SIMPLE",
                            "hasCustomLabel": false,
                            "label": "SUM(reach)",
                            "optionName": "metric_y2ea5imb0n_ifyzgnajnfd",
                            "sqlExpression": null
                        },
                        false
                    ]
                ],
                "annotation_layers": [],
                "row_limit": 10000,
                "series_columns": [
                    "channel_name_tvd"
                ],
                "series_limit": 0,
                "order_desc": true,
                "url_params": {
                    "native_filters_key": "aaAgVXCbIn24rD_9C82ooOEo2XaGgZMtAAzqV4Shet0E6AUVprSZrNgSNeKLVVYZ"
                },
                "custom_params": {},
                "custom_form_data": {},
                "time_offsets": [],
                "post_processing": [
                    {
                        "operation": "pivot",
                        "options": {
                            "index": [
                                "brand"
                            ],
                            "columns": [
                                "channel_name_tvd"
                            ],
                            "aggregates": {
                                "SUM(reach)": {
                                    "operator": "mean"
                                }
                            },
                            "drop_missing_columns": false
                        }
                    },
                    {
                        "operation": "rename",
                        "options": {
                            "columns": {
                                "SUM(reach)": null
                            },
                            "level": 0,
                            "inplace": true
                        }
                    },
                    {
                        "operation": "flatten"
                    }
                ]
            }
        ],
        "form_data": {
            "datasource": "283__table",
            "viz_type": "echarts_timeseries_bar",
            "slice_id": 926,
            "url_params": {
                "native_filters_key": "aaAgVXCbIn24rD_9C82ooOEo2XaGgZMtAAzqV4Shet0E6AUVprSZrNgSNeKLVVYZ"
            },
            "x_axis": {
                "datasourceWarning": false,
                "expressionType": "SQL",
                "label": "brand",
                "sqlExpression": "CASE\r\nWHEN length(brand) > 15\r\n   THEN CONCAT(left(brand, 15), '...')\r\nELSE brand\r\nEND"
            },
            "time_grain_sqla": "P1D",
            "x_axis_sort_asc": true,
            "x_axis_sort_series": "sum",
            "x_axis_sort_series_ascending": true,
            "metrics": [
                {
                    "aggregate": "SUM",
                    "column": {
                        "advanced_data_type": null,
                        "changed_on": "2026-01-08T03:03:57.316123",
                        "column_name": "reach",
                        "created_on": "2026-01-08T03:03:57.316115",
                        "description": null,
                        "expression": null,
                        "extra": "{}",
                        "filterable": true,
                        "groupby": true,
                        "id": 5328,
                        "is_active": true,
                        "is_dttm": false,
                        "python_date_format": null,
                        "type": "LONGLONG",
                        "type_generic": 0,
                        "uuid": "57d3108e-a0b9-402b-abe0-3ed65e21c9d2",
                        "verbose_name": null
                    },
                    "datasourceWarning": false,
                    "expressionType": "SIMPLE",
                    "hasCustomLabel": false,
                    "label": "SUM(reach)",
                    "optionName": "metric_y2ea5imb0n_ifyzgnajnfd",
                    "sqlExpression": null
                }
            ],
            "groupby": [
                "channel_name_tvd"
            ],
            "adhoc_filters": [
                {
                    "clause": "WHERE",
                    "comparator": "No filter",
                    "expressionType": "SIMPLE",
                    "isExtra": true,
                    "operator": "TEMPORAL_RANGE",
                    "subject": "date"
                }
            ],
            "order_desc": true,
            "row_limit": 10000,
            "truncate_metric": true,
            "show_empty_columns": true,
            "comparison_type": "values",
            "annotation_layers": [],
            "forecastPeriods": 10,
            "forecastInterval": 0.8,
            "orientation": "horizontal",
            "x_axis_title_margin": 15,
            "y_axis_title_margin": 15,
            "y_axis_title_position": "Left",
            "sort_series_type": "sum",
            "color_scheme": "supersetColors",
            "time_shift_color": true,
            "show_value": true,
            "stack": "Stack",
            "only_total": true,
            "show_legend": true,
            "legendType": "scroll",
            "legendOrientation": "top",
            "x_axis_time_format": "smart_date",
            "y_axis_format": ",d",
            "y_axis_bounds": [
                null,
                null
            ],
            "truncateXAxis": true,
            "rich_tooltip": true,
            "showTooltipTotal": true,
            "showTooltipPercentage": true,
            "tooltipTimeFormat": "smart_date",
            "dashboards": [],
            "extra_form_data": {
                "time_range": "DATEADD(DATETIME(\"today\"),-2, DAY) : DATEADD(DATETIME(\"today\"),-1, SECOND)"
            },
            "chart_id": 926,
            "label_colors": {
                "price": "#ffd04c",
                "price_usd": "#ffd04c",
                "count": "#ffd04c",
                "VTV1": "#ca2d1e",
                "VTV2": "#42932b",
                "VTV3": "#000191",
                "VTV5": "#9467bd",
                "VTV Cần Thơ": "#6ce5e8",
                "VTV4": "#8c564b",
                "VTV9": "#e377c2",
                "VTV5 Tây Nam Bộ": "#7f7f7f",
                "VTV8": "#bcbd22",
                "VTV7": "#2d8bba",
                "Thời sự - Chính luận": "#6BD3B3",
                "Phim dài tập": "#FCC550",
                "Đời sống": "#EE5960",
                "Tài liệu - Phóng sự": "#408184",
                "Giải trí": "#66CBE2",
                "Giáo dục - Đào tạo": "#5470C6",
                "Dành cho trẻ em": "#ffb2f3",
                "Thể thao": "#FF874E",
                "Sự kiện": "#03748E",
                "Quảng bá": "#8c564a",
                "Phim truyện": "#C9BBAB",
                "Quảng cáo": "#B17BAA"
            },
            "shared_label_colors": [
                "2 PHONG (FERTIL...",
                "ABBANK",
                "AGRIBANK",
                "AJINOMOTO VIETN...",
                "AQUAFINA",
                "AVENUE",
                "BAO KHI KHANG (...",
                "BENH VIEN DA KH...",
                "BIA HA NOI",
                "BIDV (BANK)",
                "BINH VI THAI MI...",
                "BLIVE MART",
                "BOGANIC PREMIUM...",
                "BONCHA (RTD GRE...",
                "BOSS COFFEE (RT...",
                "BUDWEISER (BEER...",
                "BYEBYE-FYVER",
                "C2 (RTD GREEN T...",
                "CA HOI NA UY SF...",
                "CASPER (AIR CON...",
                "CHANTE (WASHING...",
                "CHARMORA CITY N...",
                "CLEAR MAT LANH",
                "CLOSEUP BAC HA",
                "COCA-COLA (AERA...",
                "COLGATE (TOOTHP...",
                "COMFORT (FABRIC...",
                "COOL AIR",
                "DA HUONG (FEMIN...",
                "DANISA",
                "DAP PHU MY",
                "DAU TRAU (FERTI...",
                "DEF PHU MY XANH",
                "DONG TRUNG HA T...",
                "DOVE (HAIR CARE...",
                "DOWNY (FABRIC C...",
                "DR.THANH (RTD H...",
                "DREAME",
                "DUNG DICH XIT H...",
                "ENTEROGERMINA (...",
                "FAMI (SOY MILK)",
                "FLC QUY NHON BE...",
                "FUZE TEA",
                "GIA BY KITA",
                "GILLETTE (RAZOR...",
                "GLOBAL NUTRITIO...",
                "Giải trí",
                "HANOI (BEER)",
                "HDBANK PRIORITY",
                "HEAD & SHOULDER...",
                "HEAD HONDA",
                "HOA PHAT (TOLE)",
                "HOA PHAT STEEL ...",
                "HOAT HUYET - NH...",
                "HOAT HUYET DUON...",
                "HONDA",
                "HONDA CUVE",
                "HUDA (BEER)",
                "HUU CO PHU MY O...",
                "HYGIENE",
                "HYUNDAI-SANTAFE...",
                "ICH NIEU KHANG ...",
                "ICH THAN VUONG ...",
                "IMPERIA SKY PAR...",
                "INTIMATE",
                "IPHONE - APPLE ...",
                "IPHONE 17",
                "JEX (BONE & JOI...",
                "KANGAROO (WATER...",
                "KANTECH",
                "KAROFI (WATER F...",
                "KHU Y TE KY THU...",
                "KIEU BY KITA",
                "KNORR (SEASONIN...",
                "LAY'S (POTATO C...",
                "LINEABON (VITAM...",
                "LIVOTEC",
                "LOTTE CHOCOLAT",
                "MARIAL GEL",
                "MASTER MEDIA AC...",
                "MASTERISE GROUP",
                "MB (BANK)",
                "MEAT DELI (PORK...",
                "MERIVISTA",
                "MIK GROUP",
                "MILO (ENERGY PO...",
                "MOC CHAU CREAME...",
                "MOLFIX OXY",
                "MOOZI",
                "NAGAKAWA (AIR C...",
                "NESCAFE (INSTAN...",
                "NEXTG CAL (VITA...",
                "NGUYEN XUAN (HE...",
                "NOBLE PALACE TA...",
                "NOBLE WEST LAKE...",
                "NUI THAN TAI MI...",
                "NUMBER 1 (ENERG...",
                "NUMBER 1- 0 DO ...",
                "OCEAN EDU",
                "OMACHI (INSTANT...",
                "OMO (WASHING LI...",
                "OREO (BISCUIT)",
                "P/S (TOOTHPASTE...",
                "PANTENE PRO-V (...",
                "PETRO VIETNAM (...",
                "PETROLIMEX VIET...",
                "PHENIKAA UNIVER...",
                "PLEIKU GOLF CLU...",
                "PONNIE",
                "PSA",
                "PVCOMBANK",
                "Phim dài tập",
                "Quảng cáo",
                "RED BULL (ENERG...",
                "ROMA D-MAXX MAR...",
                "S-LIGHT TOWER",
                "SALONPAS (PAIN ...",
                "SAMSUNG",
                "SCTV CHANNELS (...",
                "SEABANK",
                "SENSODYNE (TOOT...",
                "SIEU THI DIEN M...",
                "SODA",
                "SUA RUA MAT LEN...",
                "SUBAC (ANTISEPT...",
                "SUMIKURA",
                "SUN FESTO TOWN",
                "SUN GROUP VIETN...",
                "SUN PHUQUOC AIR...",
                "SUNLIGHT (DISH ...",
                "SUNSILK (HAIR C...",
                "SURF (WASHING L...",
                "TAM BINH (DRINK...",
                "TEA+ (RTD OLONG...",
                "TEA+ (RTD TEA)",
                "TEBAGOCEL",
                "TECHCOMBANK",
                "TH TRUE FOOD (F...",
                "TH TRUE MILK (F...",
                "THACO AGRI (AGR...",
                "THACO LOGISTICS",
                "THANH HANG BEAU...",
                "THE MAGNOLIA PR...",
                "THE PARKLAND",
                "THEP VAS",
                "TIFOPLAST - TIE...",
                "TIGER (BEER)",
                "TROPICANA TWIST...",
                "TRUONG HAI AUTO...",
                "Thể thao",
                "Thời sự - Chính luận",
                "UNIVERSITY OF E...",
                "VIETCOMBANK",
                "VIETINBANK",
                "VIETJET AIR",
                "VIETLOTT (LOTTE...",
                "VIGLACERA",
                "VINAMILK",
                "VINAMILK (EATIN...",
                "VINAMILK (FRESH...",
                "VINAPHONE (MOBI...",
                "VINFAST",
                "VINHOMES GLOBAL...",
                "VINHOMES GREEN ...",
                "VINHOMES HAI VA...",
                "VINHOMES SAIGON...",
                "VINMEC HEALTHCA...",
                "VPBANK",
                "VPBANK - APPLE ...",
                "VPP HAI TIEN",
                "VTV1",
                "VTV2",
                "VTV3",
                "VTV4",
                "VTV6",
                "VTV8",
                "VTV9",
                "VUONG BAO (PROS...",
                "VUONG LAO KIEN",
                "Vui lòng chọn filter Brand",
                "WAKE-UP 247 (EN...",
                "YAKULT (DRINKIN...",
                "YAMAHA",
                "ZOZO IMUSE (COL...",
                "price",
                "Đời sống"
            ],
            "map_label_colors": {
                "SMART_TV": "#1FA8C9",
                "MOBILE": "#454E7C",
                "PC/Lap": "#5AC189",
                "TABLET": "#FF7F44",
                "Chưa xem hết": "#6BD3B3",
                "Xem hết": "#FCC550",
                "TECHCOMBANK": "#1FA8C9",
                "MASTERISE GROUP": "#454E7C",
                "PETROLIMEX VIET...": "#454E7C",
                "IMPERIA SKY PAR...": "#5AC189",
                "VINHOMES GLOBAL...": "#FF7F44",
                "TIFOPLAST - TIE...": "#666666",
                "MIK GROUP": "#A868B7",
                "WAKE-UP 247 (EN...": "#E04355",
                "VINHOMES GREEN ...": "#FCC700",
                "FAMI (SOY MILK)": "#3CCCCB",
                "THE PARKLAND": "#a39779",
                "CHANTE (WASHING...": "#A38F79",
                "PETRO VIETNAM (...": "#fdfc80",
                "HUDA (BEER)": "#8FD3E4",
                "VPP HAI TIEN": "#3CCCCB",
                "OMACHI (INSTANT...": "#8fb1e4",
                "MILO (ENERGY PO...": "#efa8a1",
                "SUA RUA MAT LEN...": "#a2a379",
                "MEAT DELI (PORK...": "#FCC700",
                "AVENUE": "#A1A6BD",
                "NOBLE WEST LAKE...": "#ACE1C4",
                "TAM BINH (DRINK...": "#FEC0A1",
                "DANISA": "#FCC700",
                "HONDA": "#B2B2B2",
                "VINHOMES SAIGON...": "#EFA1AA",
                "COLGATE (TOOTHP...": "#D3B3DA",
                "BENH VIEN DA KH...": "#FDE380",
                "S-LIGHT TOWER": "#9EE5E5",
                "VIETINBANK": "#b2b2b2",
                "SUN GROUP VIETN...": "#9EE5E5",
                "SUN FESTO TOWN": "#D1C6BC",
                "DUNG DICH XIT H...": "#5AC189",
                "HEAD HONDA": "#A38F79",
                "HEAD & SHOULDER...": "#8FD3E4",
                "HOA PHAT STEEL ...": "#FDE380",
                "VINFAST": "#FDE380",
                "NEXTG CAL (VITA...": "#9EE5E5",
                "HANOI (BEER)": "#fdfc80",
                "C2 (RTD GREEN T...": "#5ac19e",
                "COOL AIR": "#A1A6BD",
                "TEA+ (RTD TEA)": "#5AC189",
                "RED BULL (ENERG...": "#3CCCCB",
                "KNORR (SEASONIN...": "#b068b7",
                "BOGANIC PREMIUM...": "#45537c",
                "VIGLACERA": "#ACE1C4",
                "BINH VI THAI MI...": "#47457c",
                "AQUAFINA": "#ffa444",
                "BOSS COFFEE (RT...": "#ffa444",
                "THEP VAS": "#e05043",
                "DOWNY (FABRIC C...": "#FEC0A1",
                "THE MAGNOLIA PR...": "#8fc2e4",
                "KAROFI (WATER F...": "#b768b6",
                "THANH HANG BEAU...": "#fed3a1",
                "PSA": "#4c457c",
                "ZOZO IMUSE (COL...": "#454E7C",
                "LOTTE CHOCOLAT": "#47457c",
                "PANTENE PRO-V (...": "#B2B2B2",
                "FUZE TEA": "#b768ae",
                "GILLETTE (RAZOR...": "#EFA1AA",
                "JEX (BONE & JOI...": "#45497c",
                "DA HUONG (FEMIN...": "#FEC0A1",
                "YAKULT (DRINKIN...": "#e06043",
                "DR.THANH (RTD H...": "#FF7F44",
                "MB (BANK)": "#D3B3DA",
                "SUN PHUQUOC AIR...": "#9ed7e5",
                "SURF (WASHING L...": "#454E7C",
                "CLEAR MAT LANH": "#666666",
                "DOVE (HAIR CARE...": "#52457c",
                "NGUYEN XUAN (HE...": "#9ed0e5",
                "OMO (WASHING LI...": "#1f86c9",
                "HYGIENE": "#fcf900",
                "SUNSILK (HAIR C...": "#3cb0cc",
                "BAO KHI KHANG (...": "#1f75c9",
                "ICH NIEU KHANG ...": "#f1fd80",
                "DREAME": "#1f97c9",
                "MARIAL GEL": "#fed3a1",
                "ABBANK": "#a2a1bd",
                "BIA HA NOI": "#ace1cf",
                "ICH THAN VUONG ...": "#dab3d9",
                "TROPICANA TWIST...": "#d1cabc",
                "TH TRUE MILK (F...": "#A868B7",
                "CLOSEUP BAC HA": "#fcf900",
                "VUONG BAO (PROS...": "#8fc2e4",
                "TEBAGOCEL": "#b768b6",
                "MOLFIX OXY": "#A1A6BD",
                "NUMBER 1- 0 DO ...": "#3cb0cc",
                "AGRIBANK": "#e04345",
                "MERIVISTA": "#a39779",
                "MOC CHAU CREAME...": "#ffb744",
                "SEABANK": "#E04355",
                "HOA PHAT (TOLE)": "#a2a1bd",
                "PVCOMBANK": "#ace1cf",
                "LAY'S (POTATO C...": "#D1C6BC",
                "THACO LOGISTICS": "#b2b2b2",
                "INTIMATE": "#efa8a1",
                "TRUONG HAI AUTO...": "#8fb9e4",
                "SODA": "#1f86c9",
                "PLEIKU GOLF CLU...": "#dab3d9",
                "FLC QUY NHON BE...": "#9ed7e5",
                "NUI THAN TAI MI...": "#5ac193",
                "COUNT_DISTINCT(gr)": "#6BD3B3",
                "Vui lòng chọn filter Brand": "#FCC550",
                "COUNT_DISTINCT(prd)": "#6BD3B3",
                "CHARMORA CITY N...": "#E04355",
                "KANGAROO (WATER...": "#5AC189",
                "NOBLE PALACE TA...": "#ACE1C4",
                "OCEAN EDU": "#D1C6BC",
                "NAGAKAWA (AIR C...": "#FF7F44",
                "VTV6": "#1FA8C9"
            },
            "own_color_scheme": "supersetColors",
            "extra_filters": [],
            "force": false,
            "result_format": "json",
            "result_type": "full",
            heavy: true
        },
        "result_format": "json",
        "result_type": "full"
    }
};