export const reachBarChartChannelPayload = {
    url: `${import.meta.env.VITE_API_DOMAIN}/api/v1/chart/data?form_data=%7B%22slice_id%22%3A926%7D&dashboard_id=54`,
    payload: {
        "datasource": {
            "id": 283,
            "type": "table"
        },
        "force": false,
        "queries": [
            {
                "time_range": "DATEADD(DATETIME(\"today\"),-2, DAY) : DATEADD(DATETIME(\"today\"),-1, SECOND)",
                "filters": [
                    {
                        "col": "date",
                        "op": "TEMPORAL_RANGE",
                        "val": "No filter"
                    }
                ],
                "extras": {
                    "time_grain_sqla": "P1D",
                    "having": "",
                    "where": ""
                },
                "applied_time_extras": {},
                "columns": [
                    {
                        "timeGrain": "P1D",
                        "columnType": "BASE_AXIS",
                        "datasourceWarning": false,
                        "expressionType": "SQL",
                        "label": "brand",
                        "sqlExpression": "CASE\r\nWHEN length(brand) > 15\r\n   THEN CONCAT(left(brand, 15), '...')\r\nELSE brand\r\nEND"
                    },
                    "channel_name_tvd"
                ],
                "metrics": [
                    {
                        "aggregate": "SUM",
                        "column": {
                            "advanced_data_type": null,
                            "changed_on": "2026-01-08T03:03:57.316123",
                            "column_name": "reach",
                            "created_on": "2026-01-08T03:03:57.316115",
                            "description": null,
                            "expression": null,
                            "extra": "{}",
                            "filterable": true,
                            "groupby": true,
                            "id": 5328,
                            "is_active": true,
                            "is_dttm": false,
                            "python_date_format": null,
                            "type": "LONGLONG",
                            "type_generic": 0,
                            "uuid": "57d3108e-a0b9-402b-abe0-3ed65e21c9d2",
                            "verbose_name": null
                        },
                        "datasourceWarning": false,
                        "expressionType": "SIMPLE",
                        "hasCustomLabel": false,
                        "label": "SUM(reach)",
                        "optionName": "metric_y2ea5imb0n_ifyzgnajnfd",
                        "sqlExpression": null
                    }
                ],
                "orderby": [
                    [
                        {
                            "aggregate": "SUM",
                            "column": {
                                "advanced_data_type": null,
                                "changed_on": "2026-01-08T03:03:57.316123",
                                "column_name": "reach",
                                "created_on": "2026-01-08T03:03:57.316115",
                                "description": null,
                                "expression": null,
                                "extra": "{}",
                                "filterable": true,
                                "groupby": true,
                                "id": 5328,
                                "is_active": true,
                                "is_dttm": false,
                                "python_date_format": null,
                                "type": "LONGLONG",
                                "type_generic": 0,
                                "uuid": "57d3108e-a0b9-402b-abe0-3ed65e21c9d2",
                                "verbose_name": null
                            },
                            "datasourceWarning": false,
                            "expressionType": "SIMPLE",
                            "hasCustomLabel": false,
                            "label": "SUM(reach)",
                            "optionName": "metric_y2ea5imb0n_ifyzgnajnfd",
                            "sqlExpression": null
                        },
                        false
                    ]
                ],
                "annotation_layers": [],
                "row_limit": 10000,
                "series_columns": [
                    "channel_name_tvd"
                ],
                "series_limit": 0,
                "order_desc": true,
                "url_params": {
                    "native_filters_key": "izCWMxuz3zLyy85Am8B9r6Oe-RAKlM2ks_Dl5zdU4qH4Lqte32sFHq6Y8UDE5WbN"
                },
                "custom_params": {},
                "custom_form_data": {},
                "time_offsets": [],
                "post_processing": [
                    {
                        "operation": "pivot",
                        "options": {
                            "index": [
                                "brand"
                            ],
                            "columns": [
                                "channel_name_tvd"
                            ],
                            "aggregates": {
                                "SUM(reach)": {
                                    "operator": "mean"
                                }
                            },
                            "drop_missing_columns": false
                        }
                    },
                    {
                        "operation": "rename",
                        "options": {
                            "columns": {
                                "SUM(reach)": null
                            },
                            "level": 0,
                            "inplace": true
                        }
                    },
                    {
                        "operation": "flatten"
                    }
                ]
            }
        ],
        "form_data": {
            "datasource": "283__table",
            "viz_type": "echarts_timeseries_bar",
            "slice_id": 926,
            "url_params": {
                "native_filters_key": "izCWMxuz3zLyy85Am8B9r6Oe-RAKlM2ks_Dl5zdU4qH4Lqte32sFHq6Y8UDE5WbN"
            },
            "x_axis": {
                "datasourceWarning": false,
                "expressionType": "SQL",
                "label": "brand",
                "sqlExpression": "CASE\r\nWHEN length(brand) > 15\r\n   THEN CONCAT(left(brand, 15), '...')\r\nELSE brand\r\nEND"
            },
            "time_grain_sqla": "P1D",
            "x_axis_sort_asc": true,
            "x_axis_sort_series": "sum",
            "x_axis_sort_series_ascending": true,
            "metrics": [
                {
                    "aggregate": "SUM",
                    "column": {
                        "advanced_data_type": null,
                        "changed_on": "2026-01-08T03:03:57.316123",
                        "column_name": "reach",
                        "created_on": "2026-01-08T03:03:57.316115",
                        "description": null,
                        "expression": null,
                        "extra": "{}",
                        "filterable": true,
                        "groupby": true,
                        "id": 5328,
                        "is_active": true,
                        "is_dttm": false,
                        "python_date_format": null,
                        "type": "LONGLONG",
                        "type_generic": 0,
                        "uuid": "57d3108e-a0b9-402b-abe0-3ed65e21c9d2",
                        "verbose_name": null
                    },
                    "datasourceWarning": false,
                    "expressionType": "SIMPLE",
                    "hasCustomLabel": false,
                    "label": "SUM(reach)",
                    "optionName": "metric_y2ea5imb0n_ifyzgnajnfd",
                    "sqlExpression": null
                }
            ],
            "groupby": [
                "channel_name_tvd"
            ],
            "adhoc_filters": [
                {
                    "clause": "WHERE",
                    "comparator": "No filter",
                    "expressionType": "SIMPLE",
                    "isExtra": true,
                    "operator": "TEMPORAL_RANGE",
                    "subject": "date"
                }
            ],
            "order_desc": true,
            "row_limit": 10000,
            "truncate_metric": true,
            "show_empty_columns": true,
            "comparison_type": "values",
            "annotation_layers": [],
            "forecastPeriods": 10,
            "forecastInterval": 0.8,
            "orientation": "horizontal",
            "x_axis_title_margin": 15,
            "y_axis_title_margin": 15,
            "y_axis_title_position": "Left",
            "sort_series_type": "sum",
            "color_scheme": "supersetColors",
            "time_shift_color": true,
            "show_value": true,
            "stack": "Stack",
            "only_total": true,
            "show_legend": true,
            "legendType": "scroll",
            "legendOrientation": "top",
            "x_axis_time_format": "smart_date",
            "y_axis_format": ",d",
            "y_axis_bounds": [
                null,
                null
            ],
            "truncateXAxis": true,
            "rich_tooltip": true,
            "showTooltipTotal": true,
            "showTooltipPercentage": true,
            "tooltipTimeFormat": "smart_date",
            "dashboards": [],
            "extra_form_data": {
                "time_range": "DATEADD(DATETIME(\"today\"),-2, DAY) : DATEADD(DATETIME(\"today\"),-1, SECOND)"
            },
            "chart_id": 926,
            "label_colors": {
                "price": "#ffd04c",
                "price_usd": "#ffd04c",
                "count": "#ffd04c",
                "VTV1": "#ca2d1e",
                "VTV2": "#42932b",
                "VTV3": "#000191",
                "VTV5": "#9467bd",
                "VTV Cần Thơ": "#6ce5e8",
                "VTV4": "#8c564b",
                "VTV9": "#e377c2",
                "VTV5 Tây Nam Bộ": "#7f7f7f",
                "VTV8": "#bcbd22",
                "VTV7": "#2d8bba",
                "Thời sự - Chính luận": "#6BD3B3",
                "Phim dài tập": "#FCC550",
                "Đời sống": "#EE5960",
                "Tài liệu - Phóng sự": "#408184",
                "Giải trí": "#66CBE2",
                "Giáo dục - Đào tạo": "#5470C6",
                "Dành cho trẻ em": "#ffb2f3",
                "Thể thao": "#FF874E",
                "Sự kiện": "#03748E",
                "Quảng bá": "#8c564a",
                "Phim truyện": "#C9BBAB",
                "Quảng cáo": "#B17BAA"
            },
            "shared_label_colors": [
                "2 PHONG (FERTIL...",
                "ABBANK",
                "AGRIBANK",
                "AJINOMOTO VIETN...",
                "ALIPAS (MEN SUP...",
                "ALLUVIA CITY",
                "AQUAFINA",
                "AVENUE",
                "BAO KHI KHANG (...",
                "BENH VIEN DA KH...",
                "BEPOS (POS SOLU...",
                "BETAGEN",
                "BIA HA NOI",
                "BIDV (BANK)",
                "BINH VI THAI MI...",
                "BLIVE MART",
                "BOGANIC PREMIUM...",
                "BONCHA (RTD GRE...",
                "BONISLEEP (ANTI...",
                "BOSS COFFEE (RT...",
                "BUDWEISER (BEER...",
                "C2 (RTD GREEN T...",
                "CA HOI NA UY SF...",
                "CASPER (AIR CON...",
                "CHANTE (WASHING...",
                "CHARMORA CITY N...",
                "CHIN-SU (CHILI ...",
                "CLEAR MAT LANH",
                "CLEAR MEN (MEN ...",
                "COCA-COLA (AERA...",
                "COLGATE (TOOTHP...",
                "COMFORT (FABRIC...",
                "COOL AIR",
                "DA HUONG (FEMIN...",
                "DANISA",
                "DAP PHU MY",
                "DARK HORSE",
                "DAU TRAU (FERTI...",
                "DEF PHU MY XANH",
                "DONG TRUNG HA T...",
                "DOVE (HAIR CARE...",
                "DOWNY (FABRIC C...",
                "DREAME",
                "DUNG DICH XIT H...",
                "DUTCH LADY OMEG...",
                "EMG EDUCATION",
                "ENTEROGERMINA (...",
                "FAMI (SOY MILK)",
                "FLC PREMIER PAR...",
                "FUZE TEA",
                "GIA BY KITA",
                "GILLETTE (RAZOR...",
                "GLOBAL NUTRITIO...",
                "GREENHN",
                "Giải trí",
                "HANOI (BEER)",
                "HDBANK PRIORITY",
                "HEAD & SHOULDER...",
                "HEAD HONDA",
                "HOA PHAT (TOLE)",
                "HOA PHAT STEEL ...",
                "HOAT HUYET - NH...",
                "HOAT HUYET DUON...",
                "HONDA",
                "HONDA CUVE",
                "HUDA (BEER)",
                "HUU CO PHU MY O...",
                "HYUNDAI-SANTAFE...",
                "ICH NIEU KHANG ...",
                "IMPERIA SKY PAR...",
                "INTIMATE",
                "IPHONE - APPLE ...",
                "IPHONE 17",
                "JEX (BONE & JOI...",
                "KANGAROO (WATER...",
                "KANTECH",
                "KAROFI (WATER F...",
                "KATIA PREMIUM V...",
                "KHUONG THAO DAN...",
                "KIEU BY KITA",
                "KNORR (SEASONIN...",
                "KOKOMI SNACKING",
                "LAY'S (POTATO C...",
                "LEE KUM KEE",
                "LIFEBUOY",
                "LINEABON (VITAM...",
                "LIVOTEC",
                "LOTTE CHOCOLAT",
                "MANULIFE",
                "MARIAL GEL",
                "MASTERISE GROUP",
                "MB (BANK)",
                "MEAT DELI (PORK...",
                "MIK GROUP",
                "MILO (ENERGY PO...",
                "MOC CHAU CREAME...",
                "MOLFIX OXY",
                "MOOZI",
                "NAGAKAWA (AIR C...",
                "NAM NGU (FISH S...",
                "NESCAFE (INSTAN...",
                "NEXTG CAL (VITA...",
                "NGUYEN XUAN (HE...",
                "NOBLE CRYSTAL R...",
                "NOBLE PALACE TA...",
                "NOBLE WEST LAKE...",
                "NUI THAN TAI MI...",
                "NUMBER 1 (ENERG...",
                "NUMBER 1- 0 DO ...",
                "OMACHI (INSTANT...",
                "OMO (WASHING LI...",
                "OREO (BISCUIT)",
                "P/S (TOOTHPASTE...",
                "PANTENE PRO-V (...",
                "PERCENT SCIENCE",
                "PETRO VIETNAM (...",
                "PETROLIMEX VIET...",
                "PHENIKAA UNIVER...",
                "PLEIKU GOLF CLU...",
                "PONNIE",
                "PSA",
                "PVCOMBANK",
                "Phim dài tập",
                "Quảng cáo",
                "RED BULL (ENERG...",
                "ROMA D-MAXX MAR...",
                "S-LIGHT TOWER",
                "SAM NHUNG BO TH...",
                "SAMSUNG",
                "SEABANK",
                "SENSODYNE (TOOT...",
                "SIEU THI DIEN M...",
                "SKYLED HA NOI",
                "SKYLED SAI GON",
                "STING (ENERGY D...",
                "SUA RUA MAT LEN...",
                "SUBAC (ANTISEPT...",
                "SUMIKURA",
                "SUN FESTO TOWN",
                "SUN GROUP VIETN...",
                "SUN PHUQUOC AIR...",
                "SUNLIGHT (DISH ...",
                "SUNSHINE GROUP",
                "SUNSHINE LEGEND...",
                "SUNSHINE RIVER ...",
                "SUNSILK (HAIR C...",
                "SURF (WASHING L...",
                "TAM BINH (DRINK...",
                "TEA+ (RTD OLONG...",
                "TEA+ (RTD TEA)",
                "TECHCOMBANK",
                "TH TRUE FOOD (F...",
                "TH TRUE MILK (F...",
                "THACO AGRI (AGR...",
                "THACO INDUSTRIE...",
                "THANH HANG BEAU...",
                "THE MAGNOLIA PR...",
                "THE PARKLAND",
                "THEP VAS",
                "TIFOPLAST - TIE...",
                "TRUONG HAI AUTO...",
                "Thể thao",
                "Thời sự - Chính luận",
                "UNIQLO (FASHION...",
                "UNIVERSITY OF E...",
                "VIETCOMBANK",
                "VIETINBANK",
                "VIETJET AIR",
                "VIGLACERA",
                "VILAZA",
                "VINACAFE (COFFE...",
                "VINAMILK",
                "VINAMILK (FRESH...",
                "VINAPHONE (MOBI...",
                "VINFAST",
                "VINHOMES GLOBAL...",
                "VINHOMES GREEN ...",
                "VINHOMES HAI VA...",
                "VINHOMES SAIGON...",
                "VINMEC HEALTHCA...",
                "VPBANK",
                "VPBANK (CREDIT ...",
                "VPBANK - APPLE ...",
                "VPP HAI TIEN",
                "VTV1",
                "VTV10",
                "VTV2",
                "VTV3",
                "VTV4",
                "VTV6",
                "VTV7",
                "VUONG BAO (PROS...",
                "Vui lòng chọn filter Brand",
                "WAKE-UP 247 (EN...",
                "YAKULT (DRINKIN...",
                "YAMAHA",
                "YOMOST",
                "YUMANGEL (STOMA...",
                "ZOZO IMUSE (COL...",
                "price",
                "Đời sống"
            ],
            "map_label_colors": {
                "VTV6": "#1FA8C9",
                "Chưa xem hết": "#6BD3B3",
                "Xem hết": "#FCC550",
                "SMART_TV": "#1FA8C9",
                "MOBILE": "#454E7C",
                "PC/Lap": "#5AC189",
                "TABLET": "#FF7F44",
                "COUNT_DISTINCT(prd)": "#6BD3B3",
                "Vui lòng chọn filter Brand": "#FCC550",
                "PETROLIMEX VIET...": "#454E7C",
                "TECHCOMBANK": "#1FA8C9",
                "VINHOMES GLOBAL...": "#FF7F44",
                "MASTERISE GROUP": "#454E7C",
                "VINHOMES GREEN ...": "#FCC700",
                "SUNSHINE GROUP": "#5AC189",
                "MIK GROUP": "#A868B7",
                "YAMAHA": "#5AC189",
                "VPBANK": "#E04355",
                "TIFOPLAST - TIE...": "#666666",
                "VINFAST": "#3CCCCB",
                "VPBANK (CREDIT ...": "#A1A6BD",
                "THE MAGNOLIA PR...": "#1FA8C9",
                "NOBLE CRYSTAL R...": "#ACE1C4",
                "EMG EDUCATION": "#B2B2B2",
                "HANOI (BEER)": "#fdfc80",
                "OMACHI (INSTANT...": "#8fb1e4",
                "IMPERIA SKY PAR...": "#5AC189",
                "CLEAR MEN (MEN ...": "#D3B3DA",
                "VIETCOMBANK": "#E04355",
                "BIA HA NOI": "#ace1cf",
                "IPHONE 17": "#A38F79",
                "WAKE-UP 247 (EN...": "#E04355",
                "CHANTE (WASHING...": "#A38F79",
                "VPP HAI TIEN": "#3CCCCB",
                "FAMI (SOY MILK)": "#3CCCCB",
                "SAMSUNG": "#A1A6BD",
                "MARIAL GEL": "#fed3a1",
                "VINHOMES SAIGON...": "#8FD3E4",
                "VINHOMES HAI VA...": "#8FD3E4",
                "BOGANIC PREMIUM...": "#45537c",
                "HUDA (BEER)": "#8FD3E4",
                "TAM BINH (DRINK...": "#FEC0A1",
                "COCA-COLA (AERA...": "#A38F79",
                "MEAT DELI (PORK...": "#FCC700",
                "ABBANK": "#a2a1bd",
                "SKYLED HA NOI": "#B2B2B2",
                "SKYLED SAI GON": "#ACE1C4",
                "PVCOMBANK": "#EFA1AA",
                "SUN FESTO TOWN": "#FDE380",
                "SUN GROUP VIETN...": "#9EE5E5",
                "HOAT HUYET - NH...": "#A868B7",
                "HEAD HONDA": "#A38F79",
                "S-LIGHT TOWER": "#9EE5E5",
                "BENH VIEN DA KH...": "#FDE380",
                "MILO (ENERGY PO...": "#efa8a1",
                "NESCAFE (INSTAN...": "#FDE380",
                "KAROFI (WATER F...": "#1FA8C9",
                "NUMBER 1 (ENERG...": "#EFA1AA",
                "RED BULL (ENERG...": "#3CCCCB",
                "P/S (TOOTHPASTE...": "#EFA1AA",
                "HOA PHAT (TOLE)": "#a2a1bd",
                "COLGATE (TOOTHP...": "#D3B3DA",
                "LOTTE CHOCOLAT": "#47457c",
                "NGUYEN XUAN (HE...": "#9ed0e5",
                "VINMEC HEALTHCA...": "#666666",
                "THE PARKLAND": "#a39779",
                "TEA+ (RTD TEA)": "#5AC189",
                "FUZE TEA": "#b768ae",
                "PETRO VIETNAM (...": "#fdfc80",
                "ICH NIEU KHANG ...": "#f1fd80",
                "PANTENE PRO-V (...": "#B2B2B2",
                "COOL AIR": "#A1A6BD",
                "DANISA": "#FCC700",
                "THANH HANG BEAU...": "#D1C6BC",
                "LIVOTEC": "#FF7F44",
                "VIETINBANK": "#b2b2b2",
                "C2 (RTD GREEN T...": "#5ac19e",
                "HONDA CUVE": "#fcf900",
                "BOSS COFFEE (RT...": "#ffa444",
                "NUMBER 1- 0 DO ...": "#9ed7e5",
                "SUNLIGHT (DISH ...": "#D3B3DA",
                "SENSODYNE (TOOT...": "#3cb0cc",
                "HEAD & SHOULDER...": "#FEC0A1",
                "LIFEBUOY": "#D1C6BC",
                "HOA PHAT STEEL ...": "#FDE380",
                "VIGLACERA": "#FEC0A1",
                "YAKULT (DRINKIN...": "#e06043",
                "MB (BANK)": "#8fc2e4",
                "GILLETTE (RAZOR...": "#666666",
                "COMFORT (FABRIC...": "#FF7F44",
                "AQUAFINA": "#ffa444",
                "CLEAR MAT LANH": "#454E7C",
                "DOWNY (FABRIC C...": "#FEC0A1",
                "KNORR (SEASONIN...": "#1f86c9",
                "NUI THAN TAI MI...": "#D3B3DA",
                "DREAME": "#1f97c9",
                "HONDA": "#B2B2B2",
                "YUMANGEL (STOMA...": "#A868B7",
                "LAY'S (POTATO C...": "#D1C6BC",
                "PSA": "#d1cabc",
                "DA HUONG (FEMIN...": "#fcf900",
                "LEE KUM KEE": "#ACE1C4",
                "MOOZI": "#9EE5E5",
                "BETAGEN": "#dab3d9",
                "VUONG BAO (PROS...": "#FDE380",
                "VPBANK - APPLE ...": "#1FA8C9",
                "NEXTG CAL (VITA...": "#ACE1C4",
                "BAO KHI KHANG (...": "#1f75c9",
                "JEX (BONE & JOI...": "#45497c",
                "COUNT_DISTINCT(gr)": "#6BD3B3",
                "KANGAROO (WATER...": "#5AC189",
                "DARK HORSE": "#B2B2B2",
                "TIFOPLAST - TIEN PHONG (PLASTIC PRODUCTS)": "#6BD3B3",
                "PETROLIMEX VIETNAM (PETROL PRODUCTS CORPORATE)": "#FCC550",
                "VINHOMES GLOBAL GATE HA LONG": "#408184",
                "VINHOMES GREEN PARADISE": "#66CBE2"
            },
            "own_color_scheme": "supersetColors",
            "extra_filters": [],
            "force": false,
            "result_format": "json",
            "result_type": "full"
        },
        "result_format": "json",
        "result_type": "full"
    }
};