export const reachBarChartChannelPayload = {
    url: `${import.meta.env.VITE_API_DOMAIN}/api/v1/chart/data?form_data=%7B%22slice_id%22%3A926%7D&dashboard_id=54`,
    payload: {
        "datasource": {
            "id": 283,
            "type": "table"
        },
        "force": false,
        "queries": [
            {
                "time_range": "DATEADD(DATETIME(\"today\"),-2, DAY) : DATEADD(DATETIME(\"today\"),-1, SECOND)",
                "filters": [
                    {
                        "col": "date",
                        "op": "TEMPORAL_RANGE",
                        "val": "No filter"
                    }
                ],
                "extras": {
                    "time_grain_sqla": "P1D",
                    "having": "",
                    "where": ""
                },
                "applied_time_extras": {},
                "columns": [
                    {
                        "timeGrain": "P1D",
                        "columnType": "BASE_AXIS",
                        "datasourceWarning": false,
                        "expressionType": "SQL",
                        "label": "brand",
                        "sqlExpression": "CASE\r\nWHEN length(brand) > 15\r\n   THEN CONCAT(left(brand, 15), '...')\r\nELSE brand\r\nEND"
                    },
                    "channel_name_tvd"
                ],
                "metrics": [
                    {
                        "aggregate": "SUM",
                        "column": {
                            "advanced_data_type": null,
                            "changed_on": "2026-01-08T03:03:57.316123",
                            "column_name": "reach",
                            "created_on": "2026-01-08T03:03:57.316115",
                            "description": null,
                            "expression": null,
                            "extra": "{}",
                            "filterable": true,
                            "groupby": true,
                            "id": 5328,
                            "is_active": true,
                            "is_dttm": false,
                            "python_date_format": null,
                            "type": "LONGLONG",
                            "type_generic": 0,
                            "uuid": "57d3108e-a0b9-402b-abe0-3ed65e21c9d2",
                            "verbose_name": null
                        },
                        "datasourceWarning": false,
                        "expressionType": "SIMPLE",
                        "hasCustomLabel": false,
                        "label": "SUM(reach)",
                        "optionName": "metric_y2ea5imb0n_ifyzgnajnfd",
                        "sqlExpression": null
                    }
                ],
                "orderby": [
                    [
                        {
                            "aggregate": "SUM",
                            "column": {
                                "advanced_data_type": null,
                                "changed_on": "2026-01-08T03:03:57.316123",
                                "column_name": "reach",
                                "created_on": "2026-01-08T03:03:57.316115",
                                "description": null,
                                "expression": null,
                                "extra": "{}",
                                "filterable": true,
                                "groupby": true,
                                "id": 5328,
                                "is_active": true,
                                "is_dttm": false,
                                "python_date_format": null,
                                "type": "LONGLONG",
                                "type_generic": 0,
                                "uuid": "57d3108e-a0b9-402b-abe0-3ed65e21c9d2",
                                "verbose_name": null
                            },
                            "datasourceWarning": false,
                            "expressionType": "SIMPLE",
                            "hasCustomLabel": false,
                            "label": "SUM(reach)",
                            "optionName": "metric_y2ea5imb0n_ifyzgnajnfd",
                            "sqlExpression": null
                        },
                        false
                    ]
                ],
                "annotation_layers": [],
                "row_limit": 10000,
                "series_columns": [
                    "channel_name_tvd"
                ],
                "series_limit": 0,
                "order_desc": true,
                "url_params": {
                    "native_filters_key": "TzLrzm8b48n779SD7KH0RB1On-iCcZUOdzOga2HPNeuje9HuCiYkNsjkuQNCukRr"
                },
                "custom_params": {},
                "custom_form_data": {},
                "time_offsets": [],
                "post_processing": [
                    {
                        "operation": "pivot",
                        "options": {
                            "index": [
                                "brand"
                            ],
                            "columns": [
                                "channel_name_tvd"
                            ],
                            "aggregates": {
                                "SUM(reach)": {
                                    "operator": "mean"
                                }
                            },
                            "drop_missing_columns": false
                        }
                    },
                    {
                        "operation": "rename",
                        "options": {
                            "columns": {
                                "SUM(reach)": null
                            },
                            "level": 0,
                            "inplace": true
                        }
                    },
                    {
                        "operation": "flatten"
                    }
                ]
            }
        ],
        "form_data": {
            "datasource": "283__table",
            "viz_type": "echarts_timeseries_bar",
            "slice_id": 926,
            "url_params": {
                "native_filters_key": "TzLrzm8b48n779SD7KH0RB1On-iCcZUOdzOga2HPNeuje9HuCiYkNsjkuQNCukRr"
            },
            "x_axis": {
                "datasourceWarning": false,
                "expressionType": "SQL",
                "label": "brand",
                "sqlExpression": "CASE\r\nWHEN length(brand) > 15\r\n   THEN CONCAT(left(brand, 15), '...')\r\nELSE brand\r\nEND"
            },
            "time_grain_sqla": "P1D",
            "x_axis_sort_asc": true,
            "x_axis_sort_series": "sum",
            "x_axis_sort_series_ascending": true,
            "metrics": [
                {
                    "aggregate": "SUM",
                    "column": {
                        "advanced_data_type": null,
                        "changed_on": "2026-01-08T03:03:57.316123",
                        "column_name": "reach",
                        "created_on": "2026-01-08T03:03:57.316115",
                        "description": null,
                        "expression": null,
                        "extra": "{}",
                        "filterable": true,
                        "groupby": true,
                        "id": 5328,
                        "is_active": true,
                        "is_dttm": false,
                        "python_date_format": null,
                        "type": "LONGLONG",
                        "type_generic": 0,
                        "uuid": "57d3108e-a0b9-402b-abe0-3ed65e21c9d2",
                        "verbose_name": null
                    },
                    "datasourceWarning": false,
                    "expressionType": "SIMPLE",
                    "hasCustomLabel": false,
                    "label": "SUM(reach)",
                    "optionName": "metric_y2ea5imb0n_ifyzgnajnfd",
                    "sqlExpression": null
                }
            ],
            "groupby": [
                "channel_name_tvd"
            ],
            "adhoc_filters": [
                {
                    "clause": "WHERE",
                    "comparator": "No filter",
                    "expressionType": "SIMPLE",
                    "isExtra": true,
                    "operator": "TEMPORAL_RANGE",
                    "subject": "date"
                }
            ],
            "order_desc": true,
            "row_limit": 10000,
            "truncate_metric": true,
            "show_empty_columns": true,
            "comparison_type": "values",
            "annotation_layers": [],
            "forecastPeriods": 10,
            "forecastInterval": 0.8,
            "orientation": "horizontal",
            "x_axis_title_margin": 15,
            "y_axis_title_margin": 15,
            "y_axis_title_position": "Left",
            "sort_series_type": "sum",
            "color_scheme": "supersetColors",
            "time_shift_color": true,
            "show_value": true,
            "stack": "Stack",
            "only_total": true,
            "show_legend": true,
            "legendType": "scroll",
            "legendOrientation": "top",
            "x_axis_time_format": "smart_date",
            "y_axis_format": ",d",
            "y_axis_bounds": [
                null,
                null
            ],
            "truncateXAxis": true,
            "rich_tooltip": true,
            "showTooltipTotal": true,
            "showTooltipPercentage": true,
            "tooltipTimeFormat": "smart_date",
            "dashboards": [],
            "extra_form_data": {
                "time_range": "DATEADD(DATETIME(\"today\"),-2, DAY) : DATEADD(DATETIME(\"today\"),-1, SECOND)"
            },
            "chart_id": 926,
            "label_colors": {
                "price": "#ffd04c",
                "price_usd": "#ffd04c",
                "count": "#ffd04c",
                "VTV1": "#ca2d1e",
                "VTV2": "#42932b",
                "VTV3": "#000191",
                "VTV5": "#9467bd",
                "VTV Cần Thơ": "#6ce5e8",
                "VTV4": "#8c564b",
                "VTV9": "#e377c2",
                "VTV5 Tây Nam Bộ": "#7f7f7f",
                "VTV8": "#bcbd22",
                "VTV7": "#2d8bba",
                "Thời sự - Chính luận": "#6BD3B3",
                "Phim dài tập": "#FCC550",
                "Đời sống": "#EE5960",
                "Tài liệu - Phóng sự": "#408184",
                "Giải trí": "#66CBE2",
                "Giáo dục - Đào tạo": "#5470C6",
                "Dành cho trẻ em": "#ffb2f3",
                "Thể thao": "#FF874E",
                "Sự kiện": "#03748E",
                "Quảng bá": "#8c564a",
                "Phim truyện": "#C9BBAB",
                "Quảng cáo": "#B17BAA"
            },
            "shared_label_colors": [
                "2 PHONG (FERTIL...",
                "7UP (AERATED SO...",
                "AGRIBANK",
                "AJINOMOTO VIETN...",
                "ALIPAS (MEN SUP...",
                "ANGELA (WOMEN S...",
                "AVENUE",
                "BAMBOO-AIRWAYS",
                "BAO KHI KHANG (...",
                "BIA HA NOI",
                "BINH VI THAI MI...",
                "BOGANIC PREMIUM...",
                "BONCHA (RTD GRE...",
                "BOSS COFFEE (RT...",
                "BRG GROUP",
                "BYEBYE-FYVER",
                "C2 (RTD GREEN T...",
                "CA HOI NA UY SF...",
                "CASPER (AIR CON...",
                "CHANTE (WASHING...",
                "CHARMORA CITY N...",
                "CLEAR MAT LANH",
                "CLEAR MEN (MEN ...",
                "CLOSEUP BAC HA",
                "COCA-COLA (AERA...",
                "COLGATE (TOOTHP...",
                "COMFORT (FABRIC...",
                "CONG TY CO PHAN...",
                "COOL AIR",
                "DA HUONG (FEMIN...",
                "DANISA",
                "DAU TRAU (FERTI...",
                "DONG TRUNG HA T...",
                "DOVE (HAIR CARE...",
                "DREAME",
                "DUNG DICH XIT H...",
                "DUTCH LADY OMEG...",
                "ENTEROGERMINA (...",
                "FUZE TEA",
                "GLUTEX (DIABETE...",
                "Giáo dục - Đào tạo",
                "Giải trí",
                "HANOI (BEER)",
                "HO TANG DUONG (...",
                "HOA PHAT (TOLE)",
                "HOA PHAT STEEL ...",
                "HOAT HUYET DUON...",
                "HOC VIEN PHONG ...",
                "HONDA CUVE",
                "HONG SAM THAI M...",
                "HONG SAM VIET N...",
                "HUU CO PHU MY O...",
                "HYGIENE",
                "HYUNDAI-SANTAFE...",
                "ICH NIEU KHANG ...",
                "IPHONE - APPLE ...",
                "JEX (BONE & JOI...",
                "KANGAROO (WATER...",
                "KANTECH",
                "KHU Y TE KY THU...",
                "KHUONG THAO DAN...",
                "KIA SORENTO",
                "KIEN TRUC NOI T...",
                "KINGSUP (MEN SU...",
                "KNORR (SEASONIN...",
                "LEE KUM KEE",
                "LOTTE CHOCOLAT",
                "MARIAL GEL",
                "MASTER MEDIA AC...",
                "MASTERISE GROUP",
                "MB (BANK)",
                "MEAT DELI (PORK...",
                "MIK GROUP",
                "MILO (ENERGY PO...",
                "MOC CHAU CREAME...",
                "MOLFIX OXY",
                "MOOZI",
                "MYTV",
                "NAGAKAWA (AIR C...",
                "NATTY (EATING &...",
                "NEXTG CAL (VITA...",
                "NGUYEN XUAN (HE...",
                "NOBLE PALACE TA...",
                "NUI THAN TAI MI...",
                "NUMBER 1 (ENERG...",
                "NUMBER 1- 0 DO ...",
                "NUOC TANG LUC 4...",
                "NUTRI BOOST (FL...",
                "OCEAN EDU",
                "OMACHI (INSTANT...",
                "OMO (WASHING LI...",
                "OREO (BISCUIT)",
                "P/S (TOOTHPASTE...",
                "PANADOL (COUGHS...",
                "PETRO VIETNAM (...",
                "PETROLIMEX VIET...",
                "PLEIKU GOLF CLU...",
                "PONNIE",
                "PSA",
                "PVCOMBANK",
                "Phim dài tập",
                "Quảng cáo",
                "RED BULL (ENERG...",
                "ROMA D-MAXX MAR...",
                "ROMANO (MEN SHA...",
                "SALONPAS (PAIN ...",
                "SCTV CHANNELS (...",
                "SEALOYALTY",
                "SENSODYNE (TOOT...",
                "STING (ENERGY D...",
                "SUA RUA MAT LEN...",
                "SUBAC (ANTISEPT...",
                "SUMIKURA",
                "SUN FESTO TOWN",
                "SUN GROUP VIETN...",
                "SUN PHUQUOC AIR...",
                "SUNLIGHT (DISH ...",
                "SUNSILK (HAIR C...",
                "SURF (WASHING L...",
                "TAM BINH (DRINK...",
                "TAM SAM DAN THA...",
                "TEA+ (RTD OLONG...",
                "TECHCOMBANK",
                "TH TRUE FOOD (F...",
                "TH TRUE MILK (F...",
                "THANH HANG BEAU...",
                "THE MAGNOLIA PR...",
                "THE PARKLAND",
                "THEP VAS",
                "TIFOPLAST - TIE...",
                "TIGER (BEER)",
                "TROPICANA TWIST...",
                "TRUONG HAI AUTO...",
                "Thể thao",
                "Thời sự - Chính luận",
                "UNIVERSITY OF E...",
                "VF8",
                "VIETINBANK",
                "VIETLOTT (LOTTE...",
                "VIGLACERA",
                "VIGLACERA (CERA...",
                "VIGLACERA KINH ...",
                "VINAMILK",
                "VINAMILK (EATIN...",
                "VINAMILK (FRESH...",
                "VINAMILK (NUT M...",
                "VINAPHONE (MOBI...",
                "VINFAST",
                "VINHOMES GLOBAL...",
                "VINHOMES GREEN ...",
                "VINHOMES HAI VA...",
                "VINHOMES SAIGON...",
                "VINMEC HEALTHCA...",
                "VPBANK",
                "VPBANK (CREDIT ...",
                "VPBANK - APPLE ...",
                "VPP HAI TIEN",
                "VTV1",
                "VTV2",
                "VTV3",
                "VTV6",
                "VTV8",
                "VTV9",
                "VUONG BAO (PROS...",
                "Vui lòng chọn filter Brand",
                "X-MEN (MEN SHAM...",
                "YAKULT (DRINKIN...",
                "YAMAHA",
                "YUMANGEL (STOMA...",
                "ZOZO IMUSE (COL...",
                "price",
                "Đời sống"
            ],
            "map_label_colors": {
                "VTV6": "#1FA8C9",
                "SMART_TV": "#1FA8C9",
                "MOBILE": "#454E7C",
                "PC/Lap": "#5AC189",
                "TABLET": "#FF7F44",
                "Chưa xem hết": "#6BD3B3",
                "Xem hết": "#FCC550",
                "TECHCOMBANK": "#1FA8C9",
                "VINHOMES GLOBAL...": "#FF7F44",
                "AVENUE": "#5AC189",
                "VINAMILK (FRESH...": "#E04355",
                "DANISA": "#FCC700",
                "IPHONE - APPLE ...": "#8FD3E4",
                "YAMAHA": "#666666",
                "AJINOMOTO VIETN...": "#A38F79",
                "MIK GROUP": "#A868B7",
                "VPP HAI TIEN": "#3CCCCB",
                "NGUYEN XUAN (HE...": "#9ed0e5",
                "MEAT DELI (PORK...": "#FCC700",
                "VINFAST": "#FDE380",
                "SENSODYNE (TOOT...": "#D1C6BC",
                "TAM BINH (DRINK...": "#FEC0A1",
                "BOGANIC PREMIUM...": "#45537c",
                "SUA RUA MAT LEN...": "#a2a379",
                "OMACHI (INSTANT...": "#8fb1e4",
                "DA HUONG (FEMIN...": "#FEC0A1",
                "ROMA D-MAXX MAR...": "#9EE5E5",
                "MILO (ENERGY PO...": "#efa8a1",
                "VINAMILK": "#B2B2B2",
                "PETROLIMEX VIET...": "#454E7C",
                "VPBANK": "#A1A6BD",
                "THE MAGNOLIA PR...": "#8fc2e4",
                "HONDA CUVE": "#EFA1AA",
                "C2 (RTD GREEN T...": "#5ac19e",
                "PONNIE": "#d1cabc",
                "HOAT HUYET DUON...": "#d1cebc",
                "SUN FESTO TOWN": "#D1C6BC",
                "SUN GROUP VIETN...": "#9EE5E5",
                "FUZE TEA": "#b768ae",
                "RED BULL (ENERG...": "#3CCCCB",
                "LOTTE CHOCOLAT": "#47457c",
                "DUNG DICH XIT H...": "#3c93cc",
                "ENTEROGERMINA (...": "#3cb0cc",
                "P/S (TOOTHPASTE...": "#ACE1C4",
                "TEA+ (RTD OLONG...": "#a39779",
                "HANOI (BEER)": "#fdfc80",
                "DUTCH LADY OMEG...": "#D3B3DA",
                "MOOZI": "#e05043",
                "OMO (WASHING LI...": "#b7689e",
                "HOA PHAT STEEL ...": "#FDE380",
                "VINHOMES GREEN ...": "#D3B3DA",
                "VPBANK - APPLE ...": "#e04345",
                "KHUONG THAO DAN...": "#b768b6",
                "CA HOI NA UY SF...": "#47457c",
                "COLGATE (TOOTHP...": "#D3B3DA",
                "HOA PHAT (TOLE)": "#FF7F44",
                "NUMBER 1 (ENERG...": "#1f86c9",
                "VINAMILK (NUT M...": "#dab3d5",
                "BONCHA (RTD GRE...": "#454e7c",
                "BOSS COFFEE (RT...": "#ffa444",
                "THEP VAS": "#e05043",
                "COMFORT (FABRIC...": "#b3fc00",
                "THE PARKLAND": "#a39779",
                "NUMBER 1- 0 DO ...": "#feeea1",
                "KIEN TRUC NOI T...": "#666666",
                "SUNLIGHT (DISH ...": "#efafa1",
                "SUMIKURA": "#ace1cf",
                "BAO KHI KHANG (...": "#1f75c9",
                "TROPICANA TWIST...": "#5ac193",
                "MOLFIX OXY": "#A1A6BD",
                "THANH HANG BEAU...": "#fed3a1",
                "BIA HA NOI": "#a39c79",
                "VIETINBANK": "#b2b2b2",
                "STING (ENERGY D...": "#e5fc00",
                "CLOSEUP BAC HA": "#E04355",
                "PSA": "#4c457c",
                "SURF (WASHING L...": "#454E7C",
                "NEXTG CAL (VITA...": "#9EE5E5",
                "ROMANO (MEN SHA...": "#5ac19e",
                "NUI THAN TAI MI...": "#1fa8c9",
                "ICH NIEU KHANG ...": "#f1fd80",
                "YAKULT (DRINKIN...": "#e06043",
                "VIGLACERA (CERA...": "#3cbfcc",
                "BYEBYE-FYVER": "#a7a1bd",
                "DREAME": "#1f97c9",
                "PETRO VIETNAM (...": "#fdfc80",
                "LEE KUM KEE": "#5ac1a8",
                "CLEAR MAT LANH": "#a4a1bd",
                "CLEAR MEN (MEN ...": "#dab3d9",
                "DOVE (HAIR CARE...": "#52457c",
                "TH TRUE MILK (F...": "#A868B7",
                "JEX (BONE & JOI...": "#45497c",
                "VIGLACERA KINH ...": "#9ed7e5",
                "SALONPAS (PAIN ...": "#ace1d9",
                "YUMANGEL (STOMA...": "#ff9244",
                "MASTER MEDIA AC...": "#fed3a1",
                "DONG TRUNG HA T...": "#ffb744",
                "VUONG BAO (PROS...": "#8fc2e4",
                "SUNSILK (HAIR C...": "#5AC189",
                "NUOC TANG LUC 4...": "#A38F79",
                "PANADOL (COUGHS...": "#8FD3E4",
                "SCTV CHANNELS (...": "#d1ccbc",
                "7UP (AERATED SO...": "#9ed7e5",
                "GLUTEX (DIABETE...": "#ACE1C4",
                "COOL AIR": "#fce000",
                "KNORR (SEASONIN...": "#b068b7",
                "MB (BANK)": "#dab3d9",
                "COUNT_DISTINCT(gr)": "#6BD3B3",
                "Vui lòng chọn filter Brand": "#FCC550",
                "COUNT_DISTINCT(prd)": "#6BD3B3",
                "ZOZO IMUSE (COL...": "#454E7C",
                "KANGAROO (WATER...": "#5AC189",
                "NUTRI BOOST (FL...": "#ACE1C4",
                "CHARMORA CITY N...": "#E04355"
            },
            "own_color_scheme": "supersetColors",
            "extra_filters": [],
            "force": false,
            "result_format": "json",
            "result_type": "full",
            heavy: true
        },
        "result_format": "json",
        "result_type": "full"
    }
};