export const allTableChartBrandProgramPayload = {
  url: `${import.meta.env.VITE_API_DOMAIN}/api/v1/chart/data?form_data=%7B%22slice_id%22%3A791%7D&dashboard_id=52`,
  payload: {
    "datasource": {
      "id": 231,
      "type": "table"
    },
    "force": false,
    "queries": [
      {
        "time_range": "DATEADD(DATETIME(\"today\"),-2, DAY) : DATEADD(DATETIME(\"today\"),-1, SECOND)",
        "filters": [
          {
            "col": "date",
            "op": "TEMPORAL_RANGE",
            "val": "No filter"
          }
        ],
        "extras": {
          "having": "",
          "where": ""
        },
        "applied_time_extras": {},
        "columns": [
          "brand",
          "program_name"
        ],
        "metrics": [
          {
            "aggregate": "SUM",
            "column": {
              "advanced_data_type": null,
              "changed_on": "2025-12-30T03:56:35.118985",
              "column_name": "no_of_spot",
              "created_on": "2025-12-30T03:56:35.118983",
              "description": null,
              "expression": null,
              "extra": "{\"warning_markdown\":null}",
              "filterable": true,
              "groupby": true,
              "id": 5121,
              "is_active": true,
              "is_dttm": false,
              "python_date_format": null,
              "type": "LONGLONG",
              "type_generic": 0,
              "uuid": "5ab4d775-dba8-4f28-a992-af64d01454d0",
              "verbose_name": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Tổng số spot",
            "optionName": "metric_3u832j7ppns_h78fcnuqcpj",
            "sqlExpression": null
          },
          {
            "aggregate": "SUM",
            "column": {
              "advanced_data_type": null,
              "changed_on": "2025-12-30T04:08:23.679433",
              "column_name": "price",
              "created_on": "2025-12-30T04:08:23.679425",
              "description": null,
              "expression": null,
              "extra": "{\"warning_markdown\":null}",
              "filterable": true,
              "groupby": true,
              "id": 5127,
              "is_active": true,
              "is_dttm": false,
              "python_date_format": null,
              "type": "DOUBLE",
              "type_generic": 0,
              "uuid": "3264d6c7-ad20-4328-bcbb-1416cd522d1c",
              "verbose_name": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Chi phí (triệu VND)",
            "optionName": "metric_zicsd7imi7s_2267c4bz4kt",
            "sqlExpression": null
          },
          {
            "aggregate": "SUM",
            "column": {
              "advanced_data_type": null,
              "changed_on": "2025-12-30T03:56:35.119084",
              "column_name": "user_view",
              "created_on": "2025-12-30T03:56:35.119083",
              "description": null,
              "expression": null,
              "extra": "{\"warning_markdown\":null}",
              "filterable": true,
              "groupby": true,
              "id": 5125,
              "is_active": true,
              "is_dttm": false,
              "python_date_format": null,
              "type": "LONGLONG",
              "type_generic": 0,
              "uuid": "922ab6c5-b8ae-44f4-875a-3c9a3b8870f6",
              "verbose_name": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Lượt xem/ Impression",
            "optionName": "metric_6xn7rilwhvo_z2f4z9mpssf",
            "sqlExpression": null
          },
          {
            "aggregate": null,
            "column": null,
            "datasourceWarning": false,
            "expressionType": "SQL",
            "hasCustomLabel": true,
            "label": "Reach",
            "optionName": "metric_lwzcxa27r4t_mbnozy4jlrn",
            "sqlExpression": "BITMAP_UNION_COUNT(reach)"
          },
          {
            "aggregate": "SUM",
            "column": {
              "advanced_data_type": null,
              "changed_on": "2025-12-30T03:56:35.118959",
              "column_name": "grp_percent",
              "created_on": "2025-12-30T03:56:35.118957",
              "description": null,
              "expression": null,
              "extra": "{\"warning_markdown\":null}",
              "filterable": true,
              "groupby": true,
              "id": 5120,
              "is_active": true,
              "is_dttm": false,
              "python_date_format": null,
              "type": "NEWDECIMAL",
              "type_generic": null,
              "uuid": "a7a9629e-aa1e-4c67-958c-0b8ef978cc20",
              "verbose_name": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "GRP (%)",
            "optionName": "metric_7v11rbk8zr_bmb0n7llae",
            "sqlExpression": null
          }
        ],
        "orderby": [
          [
            {
              "aggregate": "SUM",
              "column": {
                "advanced_data_type": null,
                "changed_on": "2025-12-30T03:56:35.118985",
                "column_name": "no_of_spot",
                "created_on": "2025-12-30T03:56:35.118983",
                "description": null,
                "expression": null,
                "extra": "{\"warning_markdown\":null}",
                "filterable": true,
                "groupby": true,
                "id": 5121,
                "is_active": true,
                "is_dttm": false,
                "python_date_format": null,
                "type": "LONGLONG",
                "type_generic": 0,
                "uuid": "5ab4d775-dba8-4f28-a992-af64d01454d0",
                "verbose_name": null
              },
              "datasourceWarning": false,
              "expressionType": "SIMPLE",
              "hasCustomLabel": true,
              "label": "Tổng số spot",
              "optionName": "metric_3u832j7ppns_h78fcnuqcpj",
              "sqlExpression": null
            },
            false
          ]
        ],
        "annotation_layers": [],
        "row_limit": 50000,
        "series_limit": 0,
        "order_desc": true,
        "url_params": {},
        "custom_params": {},
        "custom_form_data": {},
        "post_processing": [],
        "time_offsets": []
      },
      {
        "time_range": "DATEADD(DATETIME(\"today\"),-2, DAY) : DATEADD(DATETIME(\"today\"),-1, SECOND)",
        "filters": [
          {
            "col": "date",
            "op": "TEMPORAL_RANGE",
            "val": "No filter"
          }
        ],
        "extras": {
          "having": "",
          "where": ""
        },
        "applied_time_extras": {},
        "columns": [],
        "metrics": [
          {
            "aggregate": "SUM",
            "column": {
              "advanced_data_type": null,
              "changed_on": "2025-12-30T03:56:35.118985",
              "column_name": "no_of_spot",
              "created_on": "2025-12-30T03:56:35.118983",
              "description": null,
              "expression": null,
              "extra": "{\"warning_markdown\":null}",
              "filterable": true,
              "groupby": true,
              "id": 5121,
              "is_active": true,
              "is_dttm": false,
              "python_date_format": null,
              "type": "LONGLONG",
              "type_generic": 0,
              "uuid": "5ab4d775-dba8-4f28-a992-af64d01454d0",
              "verbose_name": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Tổng số spot",
            "optionName": "metric_3u832j7ppns_h78fcnuqcpj",
            "sqlExpression": null
          },
          {
            "aggregate": "SUM",
            "column": {
              "advanced_data_type": null,
              "changed_on": "2025-12-30T04:08:23.679433",
              "column_name": "price",
              "created_on": "2025-12-30T04:08:23.679425",
              "description": null,
              "expression": null,
              "extra": "{\"warning_markdown\":null}",
              "filterable": true,
              "groupby": true,
              "id": 5127,
              "is_active": true,
              "is_dttm": false,
              "python_date_format": null,
              "type": "DOUBLE",
              "type_generic": 0,
              "uuid": "3264d6c7-ad20-4328-bcbb-1416cd522d1c",
              "verbose_name": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Chi phí (triệu VND)",
            "optionName": "metric_zicsd7imi7s_2267c4bz4kt",
            "sqlExpression": null
          },
          {
            "aggregate": "SUM",
            "column": {
              "advanced_data_type": null,
              "changed_on": "2025-12-30T03:56:35.119084",
              "column_name": "user_view",
              "created_on": "2025-12-30T03:56:35.119083",
              "description": null,
              "expression": null,
              "extra": "{\"warning_markdown\":null}",
              "filterable": true,
              "groupby": true,
              "id": 5125,
              "is_active": true,
              "is_dttm": false,
              "python_date_format": null,
              "type": "LONGLONG",
              "type_generic": 0,
              "uuid": "922ab6c5-b8ae-44f4-875a-3c9a3b8870f6",
              "verbose_name": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "Lượt xem/ Impression",
            "optionName": "metric_6xn7rilwhvo_z2f4z9mpssf",
            "sqlExpression": null
          },
          {
            "aggregate": null,
            "column": null,
            "datasourceWarning": false,
            "expressionType": "SQL",
            "hasCustomLabel": true,
            "label": "Reach",
            "optionName": "metric_lwzcxa27r4t_mbnozy4jlrn",
            "sqlExpression": "BITMAP_UNION_COUNT(reach)"
          },
          {
            "aggregate": "SUM",
            "column": {
              "advanced_data_type": null,
              "changed_on": "2025-12-30T03:56:35.118959",
              "column_name": "grp_percent",
              "created_on": "2025-12-30T03:56:35.118957",
              "description": null,
              "expression": null,
              "extra": "{\"warning_markdown\":null}",
              "filterable": true,
              "groupby": true,
              "id": 5120,
              "is_active": true,
              "is_dttm": false,
              "python_date_format": null,
              "type": "NEWDECIMAL",
              "type_generic": null,
              "uuid": "a7a9629e-aa1e-4c67-958c-0b8ef978cc20",
              "verbose_name": null
            },
            "datasourceWarning": false,
            "expressionType": "SIMPLE",
            "hasCustomLabel": true,
            "label": "GRP (%)",
            "optionName": "metric_7v11rbk8zr_bmb0n7llae",
            "sqlExpression": null
          }
        ],
        "annotation_layers": [],
        "row_limit": 0,
        "row_offset": 0,
        "series_limit": 0,
        "url_params": {},
        "custom_params": {},
        "custom_form_data": {},
        "post_processing": [],
        "time_offsets": []
      }
    ],
    "form_data": {
      "datasource": "231__table",
      "viz_type": "table",
      "slice_id": 791,
      "url_params": {},
      "query_mode": "aggregate",
      "groupby": [
        "brand",
        "program_name"
      ],
      "temporal_columns_lookup": {
        "date": true
      },
      "metrics": [
        {
          "aggregate": "SUM",
          "column": {
            "advanced_data_type": null,
            "changed_on": "2025-12-30T03:56:35.118985",
            "column_name": "no_of_spot",
            "created_on": "2025-12-30T03:56:35.118983",
            "description": null,
            "expression": null,
            "extra": "{\"warning_markdown\":null}",
            "filterable": true,
            "groupby": true,
            "id": 5121,
            "is_active": true,
            "is_dttm": false,
            "python_date_format": null,
            "type": "LONGLONG",
            "type_generic": 0,
            "uuid": "5ab4d775-dba8-4f28-a992-af64d01454d0",
            "verbose_name": null
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": true,
          "label": "Tổng số spot",
          "optionName": "metric_3u832j7ppns_h78fcnuqcpj",
          "sqlExpression": null
        },
        {
          "aggregate": "SUM",
          "column": {
            "advanced_data_type": null,
            "changed_on": "2025-12-30T04:08:23.679433",
            "column_name": "price",
            "created_on": "2025-12-30T04:08:23.679425",
            "description": null,
            "expression": null,
            "extra": "{\"warning_markdown\":null}",
            "filterable": true,
            "groupby": true,
            "id": 5127,
            "is_active": true,
            "is_dttm": false,
            "python_date_format": null,
            "type": "DOUBLE",
            "type_generic": 0,
            "uuid": "3264d6c7-ad20-4328-bcbb-1416cd522d1c",
            "verbose_name": null
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": true,
          "label": "Chi phí (triệu VND)",
          "optionName": "metric_zicsd7imi7s_2267c4bz4kt",
          "sqlExpression": null
        },
        {
          "aggregate": "SUM",
          "column": {
            "advanced_data_type": null,
            "changed_on": "2025-12-30T03:56:35.119084",
            "column_name": "user_view",
            "created_on": "2025-12-30T03:56:35.119083",
            "description": null,
            "expression": null,
            "extra": "{\"warning_markdown\":null}",
            "filterable": true,
            "groupby": true,
            "id": 5125,
            "is_active": true,
            "is_dttm": false,
            "python_date_format": null,
            "type": "LONGLONG",
            "type_generic": 0,
            "uuid": "922ab6c5-b8ae-44f4-875a-3c9a3b8870f6",
            "verbose_name": null
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": true,
          "label": "Lượt xem/ Impression",
          "optionName": "metric_6xn7rilwhvo_z2f4z9mpssf",
          "sqlExpression": null
        },
        {
          "aggregate": null,
          "column": null,
          "datasourceWarning": false,
          "expressionType": "SQL",
          "hasCustomLabel": true,
          "label": "Reach",
          "optionName": "metric_lwzcxa27r4t_mbnozy4jlrn",
          "sqlExpression": "BITMAP_UNION_COUNT(reach)"
        },
        {
          "aggregate": "SUM",
          "column": {
            "advanced_data_type": null,
            "changed_on": "2025-12-30T03:56:35.118959",
            "column_name": "grp_percent",
            "created_on": "2025-12-30T03:56:35.118957",
            "description": null,
            "expression": null,
            "extra": "{\"warning_markdown\":null}",
            "filterable": true,
            "groupby": true,
            "id": 5120,
            "is_active": true,
            "is_dttm": false,
            "python_date_format": null,
            "type": "NEWDECIMAL",
            "type_generic": null,
            "uuid": "a7a9629e-aa1e-4c67-958c-0b8ef978cc20",
            "verbose_name": null
          },
          "datasourceWarning": false,
          "expressionType": "SIMPLE",
          "hasCustomLabel": true,
          "label": "GRP (%)",
          "optionName": "metric_7v11rbk8zr_bmb0n7llae",
          "sqlExpression": null
        }
      ],
      "all_columns": [],
      "percent_metrics": [],
      "adhoc_filters": [
        {
          "clause": "WHERE",
          "comparator": "No filter",
          "expressionType": "SIMPLE",
          "operator": "TEMPORAL_RANGE",
          "subject": "date"
        }
      ],
      "order_by_cols": [],
      "row_limit": 50000,
      "server_page_length": 10,
      "order_desc": true,
      "show_totals": true,
      "table_timestamp_format": "smart_date",
      "include_search": true,
      "allow_render_html": true,
      "column_config": {
        "Chi phí (triệu VND)": {
          "d3NumberFormat": ",.2f"
        },
        "GRP (%)": {
          "d3NumberFormat": ",.1f"
        },
        "Lượt xem/ Impression": {
          "d3NumberFormat": ",d"
        },
        "Reach": {
          "d3NumberFormat": ",d"
        },
        "Tổng số spot": {
          "d3NumberFormat": ",d"
        }
      },
      "show_cell_bars": false,
      "color_pn": true,
      "comparison_color_scheme": "Green",
      "conditional_formatting": [
        {
          "colorScheme": "#ACE1C4",
          "column": "Tổng số spot",
          "operator": "None"
        },
        {
          "colorScheme": "#ACE1C4",
          "column": "Chi phí (triệu VND)",
          "operator": "None"
        },
        {
          "colorScheme": "#ACE1C4",
          "column": "Lượt xem/ Impression",
          "operator": "None"
        },
        {
          "colorScheme": "#ACE1C4",
          "column": "Reach",
          "operator": "None"
        },
        {
          "colorScheme": "#ACE1C4",
          "column": "GRP (%)",
          "operator": "None"
        }
      ],
      "comparison_type": "values",
      "dashboards": [
        52
      ],
      "extra_form_data": {
        "time_range": "DATEADD(DATETIME(\"today\"),-2, DAY) : DATEADD(DATETIME(\"today\"),-1, SECOND)"
      },
      "chart_id": 791,
      "label_colors": {
        "price": "#ffd04c",
        "price_usd": "#ffd04c",
        "count": "#ffd04c",
        "VTV1": "#ca2d1e",
        "VTV2": "#42932b",
        "VTV3": "#000191",
        "VTV5": "#9467bd",
        "VTV Cần Thơ": "#6ce5e8",
        "VTV4": "#8c564b",
        "VTV9": "#e377c2",
        "VTV5 Tây Nam Bộ": "#7f7f7f",
        "VTV8": "#bcbd22",
        "VTV7": "#2d8bba",
        "Thời sự - Chính luận": "#6BD3B3",
        "Phim dài tập": "#FCC550",
        "Đời sống": "#EE5960",
        "Tài liệu - Phóng sự": "#408184",
        "Giải trí": "#66CBE2",
        "Giáo dục - Đào tạo": "#5470C6",
        "Dành cho trẻ em": "#ffb2f3",
        "Thể thao": "#FF874E",
        "Sự kiện": "#03748E",
        "Quảng bá": "#8c564a",
        "Phim truyện": "#C9BBAB",
        "Quảng cáo": "#B17BAA"
      },
      "shared_label_colors": [
        "1.Sáng (0h - 11h)",
        "2.Trưa (11h - 14h)",
        "3.Chiều (14h - 18h)",
        "4.Tối (18h - 24h)",
        "<NULL>",
        "ABBOTT LABORATO...",
        "ACECOOK VIETNAM...",
        "AGRIBANK VN (VI...",
        "AJINOMOTO VIETN...",
        "BAO THANH (COUGHS FLU)",
        "BENH VIEN PHAP ...",
        "BIDV (BANK FOR ...",
        "BINH DIEN FERTI...",
        "BINH SON REFINI...",
        "BO PHE NAM HA (COUGH DROP SUPP.)",
        "BONCHA (RTD GREEN TEA)",
        "BOTANIA CO., LT...",
        "BRG GROUP",
        "CASPER ELECTRIC...",
        "CASTROL BP PETC...",
        "CHIN-SU FOODS (CORPORATE)",
        "COCA-COLA VIETN...",
        "COLGATE (TOOTHPASTE)",
        "COLGATE-PALMOLI...",
        "COMPACT",
        "CONG TY CO PHAN TAP DOAN TRUONG HAI",
        "CONG TY CO PHAN...",
        "CONG TY CP BANH...",
        "CONG TY CP DAY ...",
        "CONG TY CP TAP ...",
        "CONG TY DUOC PH...",
        "CONG TY HONDA V...",
        "CONG TY TNHH AM...",
        "CONG TY TNHH AP...",
        "CONG TY TNHH BE...",
        "CONG TY TNHH BO...",
        "CONG TY TNHH CA...",
        "CONG TY TNHH CH...",
        "CONG TY TNHH DA...",
        "CONG TY TNHH DU...",
        "CONG TY TNHH GA...",
        "CONG TY TNHH GI...",
        "CONG TY TNHH HA...",
        "CONG TY TNHH ME...",
        "CONG TY TNHH MT...",
        "CONG TY TNHH NA...",
        "CONG TY TNHH SO...",
        "CONG TY TNHH TA...",
        "CONG TY TNHH TM...",
        "CONG TY TNHH TU...",
        "CONG TY TNHH UN...",
        "CÔNG TY CỔ PHẦN...",
        "DANISA",
        "DECOLGEN",
        "DHC GROUP",
        "DONG LUC GROUP",
        "DONG NAM A JS B...",
        "Dành cho trẻ em",
        "ECO PHARMACY JS...",
        "FOBIC CO., LTD",
        "FONTERRA CO-OPE...",
        "FORIPHARM (NO.3...",
        "FRIESLANDCAMPIN...",
        "FUMAKILLA VIETN...",
        "GLAXO SMITHKLIN...",
        "GOODY",
        "Giáo dục - Đào tạo",
        "Giải trí",
        "HANOI BEVERAGE ...",
        "HCMC HOUSING DE...",
        "HEINEKEN VIETNA...",
        "HISAMITSU VIETN...",
        "HOA LINH PHARMA...",
        "HOA PHAT (TOLE)",
        "HOA PHAT STEEL ...",
        "HOA SEN GROUP",
        "HOANG MAI PRODU...",
        "HOAT HUYET - NHAT NHAT (TRAD. BRAIN HEALTH MED.)",
        "HONG KONG BEAUT...",
        "HUUNGHI FOODS J...",
        "HYUNDAI THANH C...",
        "I.P VIETNAM CO....",
        "IMC (INT'L MEDI...",
        "KANGAROO GROUP",
        "KHUONG THAO DAN (BONE & JOINT SUPP.)",
        "LEE KUM KEE COM...",
        "LOHACO",
        "LONG HAI CO., L...",
        "LPBANK",
        "MASAN CONSUMER ...",
        "MIKADO TECHNOLO...",
        "MILITARY COMMER...",
        "NAM DUOC JS CO.",
        "NAM HA PHARMA J...",
        "NAM NGU (FISH SAUCE)",
        "NATIONAL PHARMA...",
        "NESTLE VIETNAM ...",
        "NGAN HANG THUON...",
        "NGAN HANG TMCP ...",
        "NHAT NHAT TRADI...",
        "P&G VIETNAM CO....",
        "PEPSICO FOODS V...",
        "PETROVIETNAM",
        "PETROVIETNAM CA...",
        "PHUN XAM TU NHI...",
        "PV GAS - PETROVIETNAM GAS JOINT STOCK CORPORATION",
        "Phim dài tập",
        "Phim điện ảnh",
        "Quảng bá",
        "Quảng cáo",
        "RED BULL VIETNA...",
        "RICHY-KENJU (BISCUIT)",
        "ROCKSTAR (ENERGY DRINKS)",
        "ROHTO MENTHOLAT...",
        "SABECO (SAIGON ...",
        "SAIGON TOURIST ...",
        "SAM NHUNG BO THAN TW3 (ORIENTAL KIDNEY RESTORATIVE MEDICINE)",
        "SANOFI-AVENTIS ...",
        "SHOPEE CO., LTD",
        "SKODA AUTO A.S",
        "SOHACO GROUP",
        "SUN GROUP CORPO...",
        "SUN GROUP VIETNAM (REAL ESTATE COMPANY)",
        "SUN PHUQUOC AIRWAYS",
        "SUNSHINE GROUP",
        "SUNTORY PEPSICO...",
        "Sự kiện - Đặc biệt",
        "TAM ANH HOSPITA...",
        "TAM BINH (DRINK SUPP.)",
        "TAM BINH PHARMA...",
        "TAN HIEP PHAT B...",
        "TECHCOMBANK",
        "TH MILK FOOD JS...",
        "TH TRUE YOGURT (EATING & FLAVOURED YOGHURT)",
        "THAM MY VIEN KA...",
        "THE GIOI DI DON...",
        "THE SOUTHERN FE...",
        "THE SUNSET SUN GRAND CITY HILLSIDE RESIDENCE",
        "THEP VAS",
        "TONG CONG TY CP...",
        "TONG CONG TY VI...",
        "TRAPHACO JSC",
        "TRUONG HAI AUTO...",
        "TRUONG HAI GROU...",
        "TUNG HO STEEL V...",
        "TW3 PHARMA TRAD...",
        "Thể thao",
        "Thời sự - Chính luận",
        "Tài liệu - Phóng sự",
        "UNIBEN JS CO.",
        "UNILEVER VIETNA...",
        "UNIQLO (FASHION)",
        "URC (UNIVERSAL ...",
        "VAS GROUP",
        "VIETCOMBANK",
        "VIETINBANK (VIE...",
        "VIETNAM AIRLINE...",
        "VIETNAM FOOD IN...",
        "VIETNAM NATIONA...",
        "VIETNAM PAYMENT...",
        "VIETNAM POST & ...",
        "VIETTEL CORPORA...",
        "VIFON MI RIEU CUA",
        "VINACAFE BIEN H...",
        "VINAMILK (FRESH MILK)",
        "VINAMILK CORPOR...",
        "VINASOY",
        "VINH GIA PHARM ...",
        "VTV Cần Thơ",
        "VTV1",
        "VTV10",
        "VTV2",
        "VTV3",
        "VTV4",
        "VTV5",
        "VTV5 Tây Nam Bộ",
        "VTV5 Tây Nguyên",
        "VTV7",
        "VTV8",
        "VTV9",
        "WIPRO CONSUMER ...",
        "YAKULT VIETNAM ...",
        "YUHAN CORPORATI...",
        "ZOZO IMUSE (COLD-FLU SUPP.)",
        "price",
        "Đời sống"
      ],
      "map_label_colors": {},
      "extra_filters": [],
      "force": false,
      "result_format": "json",
      "result_type": "full"
    },
    "result_format": "json",
    "result_type": "full",
    heavy: true
  }
};