export const LABEL = {
  'channel_name_tvd': 'KÊNH',
  'rating': 'RATING\n(người/phút)',
  'RATING (người/phút)': 'RATING\n(người/phút)',
  'AveREACH (người/lượt phát)': 'AveREACH\n(người/lượt phát)',
  'ave_reach': 'AveREACH\n(người/lượt phát)',
  'ave_reach_1': 'AveREACH\n(người/lượt phát)',
  'rating%': 'RATING\n(%)',
  'RATING (%)': 'RATING\n(%)',
  'reach%': 'REACH\n(%)',
  'reach%_1': 'REACH\n(%)',
  'REACH (%)': 'REACH\n(%)',
  'minute/user/day': 'Phút/người/ngày',
  'minute_user_day': 'Phút/người/ngày',
  'Phút/người/ lượt phát': 'Phút/người/\nlượt phát',
  'minute_user_program': 'Phút/người/\nlượt phát',
  'regional_name': 'VÙNG',
  'event_category_name': 'Live/TSV',
  'province': 'TỈNH/TP',
  'program_name': 'CHƯƠNG TRÌNH',
  'firstlevel_vn': 'THỂ LOẠI',
  'name_vn': 'MÔ TẢ',
  'description': 'TÊN/TẬP',
  'start_time': 'THỜI GIAN\nBẮT ĐẦU',
  'end_time': 'THỜI GIAN\nKẾT THÚC',
  'brand': 'Nhãn',
  'product': 'Sản phẩm',
  'campaign_name': 'Chiến dịch',
  'price': 'Chi phí (Triệu VND)',
  'price_usd': 'Chi phí (USD)',
  'count': 'Số lượng',
  '%percent_price': '%Share of spend',
  '%percent_count': '%Share of spot',
  '%percent_duration': '%Share of airtime',
  '%percent_grp': '%Share of voice',
  'ads_code': 'Adcode',
  'Mã giờ': 'Adcode',
  'time_band': 'Khung giờ',
  'advertiser': 'Nhà quảng cáo',
  'Chi phí (triệu VND)': 'Chi phí (Triệu VND)',
  'week': 'Tuần',
  'spot_start_time': 'Thời gian\nbắt đầu',
  'spot_end_time': 'Thời gian\nkết thúc',
  'duration': 'Thời lượng Spot',
  'break_in_program': 'Break',
  'position_in_break': 'Position',
  'spot_type': 'Loại Spot',
  'Ngành hàng/ Group': 'Ngành hàng',
  'Nhãn hàng/ Brand': 'Nhãn hàng',
  'Nhãn': 'Nhãn hàng',
  'Dòng sản phẩm': 'Sản phẩm',
  'others': 'Thời lượng khác',
  'Tổng user truy cập VTVgo': 'Tổng user',
  'Thời lượng (phút)': 'Thời lượng'
};

export const LABEL_METRIC = {
  'rating': 'Rating',
  'ave_reach': 'Ave.Reach',
  'reach%_1': 'Ave.Reach (%)',
  'reach_timeband%': 'Ave.Reach (%)',
  'rating_timeband%': 'Rating (%)',
  'ave_reach_1': 'Ave.Reach',
  'ave_reach_timeband': 'Ave.Reach',
  'rating_timeband': 'Rating',
  'price': 'Chi phí (Triệu VND)',
  'price_usd': 'Chi phí (USD)',
  'count': 'Số lượng'
} 

export const FILTER_LABEL = {
  'channels': 'Kênh',
  'events': 'Live/TimeShift',
  'provinces': 'Tỉnh/TP',
  'regionals': 'Vùng',
  'keyCities': 'Thành phố lớn',
  'timebands': 'Khung giờ',
  'days': 'Nhóm ngày',
  'programs': 'Chương trình',
  'adCodes': 'Adscode',
  'spotTypes': 'Loại spot',
  'groups': 'Ngành hàng',
  'advertisers': 'Nhà quảng cáo',
  'products': 'Sản phẩm',
  'brands': 'Nhãn hàng',
  'campaigns': 'Chiến dịch',
  'platforms': 'Thiết bị'
}

export const VALUE_LABEL = {
  'Monday': 'Thứ hai',
  'Tuesday': 'Thứ ba',
  'Wednesday': 'Thứ tư',
  'Thursday': 'Thứ năm',
  'Friday': 'Thứ sáu',
  'Saturday': 'Thứ bảy',
  'Sunday': 'Chủ nhật',
  'InWeek': '',
  'Weekend': ''
}

export const LABEL_TABS = {
  overview: 'Tổng quan',
  channel: 'Kênh',
  program: 'Chương trình',
  rating_by_minute: 'Rating theo phút',
  revenue: 'Doanh thu',
  effective: 'Hiệu quả',
  ad_monitoring_report: 'Ad monitoring report'
}