export const LABEL = {
  'channel_name_tvd': 'KÊNH',
  'rating': 'RATING\n(người/phút)',
  'RATING (người/phút)': 'RATING\n(người/phút)',
  'AveREACH (người/lượt phát)': 'AveREACH\n(người/lượt phát)',
  'ave_reach': 'AveREACH\n(người/lượt phát)',
  'ave_reach_1': 'AveREACH\n(người/lượt phát)',
  'rating%': 'RATING\n(%)',
  'RATING (%)': 'RATING\n(%)',
  'reach%': 'REACH\n(%)',
  'reach%_1': 'REACH\n(%)',
  'REACH (%)': 'REACH\n(%)',
  'minute/user/day': 'Phút/người/ngày',
  'minute_user_day': 'Phút/người/ngày',
  'Phút/người/ lượt phát': 'Phút/người/\nlượt phát',
  'minute_user_program': 'Phút/người/\nlượt phát',
  'regional_name': 'VÙNG',
  'event_category_name': 'Live/TSV',
  'province': 'TỈNH/TP',
  'program_name': 'CHƯƠNG TRÌNH',
  'firstlevel_vn': 'THỂ LOẠI',
  'name_vn': 'MÔ TẢ',
  'description': 'TÊN/TẬP',
  'start_time': 'THỜI GIAN\nBẮT ĐẦU',
  'end_time': 'THỜI GIAN\nKẾT THÚC',
  'brand': 'Nhãn',
  'product': 'Sản phẩm',
  'campaign_name': 'Chiến dịch',
  'price': 'Chi phí (Triệu VND)',
  'price_usd': 'Chi phí (USD)',
  'count': 'Số lượng',
  '%percent_price': '%Share of spend',
  '%percent_count': '%Share of spot',
  '%percent_duration': '%Share of airtime',
  '%percent_grp': '%Share of voice',
  'ads_code': 'Adcode',
  'Mã giờ': 'Adcode',
  'time_band': 'Khung giờ',
  'advertiser': 'Nhà quảng cáo',
  'Chi phí (triệu VND)': 'Chi phí (Triệu VND)',
  'week': 'Tuần',
  'spot_start_time': 'Thời gian\nbắt đầu',
  'spot_end_time': 'Thời gian\nkết thúc',
  'duration': 'Thời lượng Spot',
  'break_in_program': 'Break',
  'position_in_break': 'Position',
  'spot_type': 'Loại Spot',
  'Ngành hàng/ Group': 'Ngành hàng',
  'Nhãn hàng/ Brand': 'Nhãn hàng',
  'Nhãn': 'Nhãn hàng',
  'Dòng sản phẩm': 'Sản phẩm',
  'others': 'TOÀN QUỐC',
  'Tổng user truy cập VTVgo': 'Tổng user',
  'Thời lượng (phút)': 'Thời lượng',
  'key_city': 'THÀNH PHỐ LỚN',
  'stage': 'GIAI ĐOẠN',
  'Trận đấu': 'TRẬN ĐẤU',
  'Thời gian bắt đầu': 'THỜI GIAN\nBẮT ĐẦU',
  'Đội tuyển': 'ĐỘI TUYỂN',
  'Số trận đấu': 'SỐ TRẬN ĐẤU',
};

export const LABEL_SPOT = {
  'channel_name_tvd': 'Kênh',
  'rating': 'RATING\n(người/phút)',
  'RATING (người/phút)': 'RATING\n(người/phút)',
  'AveREACH (người/lượt phát)': 'AveREACH\n(người/lượt phát)',
  'ave_reach': 'AveREACH\n(người/lượt phát)',
  'ave_reach_1': 'AveREACH\n(người/lượt phát)',
  'rating%': 'RATING\n(%)',
  'RATING (%)': 'RATING\n(%)',
  'reach%': 'REACH\n(%)',
  'reach%_1': 'REACH\n(%)',
  'REACH (%)': 'REACH\n(%)',
  'minute/user/day': 'Phút/người/ngày',
  'minute_user_day': 'Phút/người/ngày',
  'Phút/người/ lượt phát': 'Phút/người/\nlượt phát',
  'minute_user_program': 'Phút/người/\nlượt phát',
  'regional_name': 'VÙNG',
  'event_category_name': 'Live/TSV',
  'province': 'TỈNH/TP',
  'program_name': 'Chương trình',
  'firstlevel_vn': 'THỂ LOẠI',
  'name_vn': 'MÔ TẢ',
  'description': 'TÊN/TẬP',
  'start_time': 'THỜI GIAN\nBẮT ĐẦU',
  'end_time': 'THỜI GIAN\nKẾT THÚC',
  'brand': 'Nhãn',
  'product': 'Sản phẩm',
  'campaign_name': 'Chiến dịch',
  'price': 'Chi phí (Triệu VND)',
  'price_usd': 'Chi phí (USD)',
  'count': 'Số lượng',
  '%percent_price': '%Share of spend',
  '%percent_count': '%Share of spot',
  '%percent_duration': '%Share of airtime',
  '%percent_grp': '%Share of voice',
  'ads_code': 'Adcode',
  'Mã giờ': 'Adcode',
  'time_band': 'Khung giờ',
  'advertiser': 'Nhà quảng cáo',
  'Chi phí (triệu VND)': 'Chi phí (Triệu VND)',
  'week': 'Tuần',
  'spot_start_time': 'Thời gian\nbắt đầu',
  'spot_end_time': 'Thời gian\nkết thúc',
  'duration': 'Thời lượng Spot',
  'break_in_program': 'Break',
  'position_in_break': 'Position',
  'spot_type': 'Loại Spot',
  'Ngành hàng/ Group': 'Ngành hàng',
  'Nhãn hàng/ Brand': 'Nhãn hàng',
  'Nhãn': 'Nhãn hàng',
  'Dòng sản phẩm': 'Sản phẩm',
  'others': 'Thời lượng khác',
  'Tổng user truy cập VTVgo': 'Tổng user',
  'Thời lượng (phút)': 'Thời lượng',
  'reach': 'Reach'
};

export const LABEL_METRIC = {
  'rating': 'Rating',
  'ave_reach': 'Ave.Reach',
  'reach%_1': 'Ave.Reach (%)',
  'reach_timeband%': 'Ave.Reach (%)',
  'rating_timeband%': 'Rating (%)',
  'ave_reach_1': 'Ave.Reach',
  'ave_reach_timeband': 'Ave.Reach',
  'rating_timeband': 'Rating',
  'price': 'Chi phí (Triệu VND)',
  'price_usd': 'Chi phí (USD)',
  'count': 'Số lượng'
}

export const FILTER_LABEL = {
  'channels': 'Kênh',
  'events': 'Live/TimeShift',
  'provinces': 'Tỉnh/TP',
  'regionals': 'Vùng',
  'keyCities': 'Thành phố lớn',
  'timebands': 'Khung giờ',
  'days': 'Nhóm ngày',
  'programs': 'Chương trình',
  'adCodes': 'Adcode',
  'spotTypes': 'Loại spot',
  'groups': 'Ngành hàng',
  'advertisers': 'Nhà quảng cáo',
  'products': 'Sản phẩm',
  'brands': 'Nhãn hàng',
  'campaigns': 'Chiến dịch',
  'platforms': 'Thiết bị',
  'firstLevels': 'Thể loại'
}

export const VALUE_LABEL = {
  'Monday': 'Thứ hai',
  'Tuesday': 'Thứ ba',
  'Wednesday': 'Thứ tư',
  'Thursday': 'Thứ năm',
  'Friday': 'Thứ sáu',
  'Saturday': 'Thứ bảy',
  'Sunday': 'Chủ nhật',
  'InWeek': '',
  'Weekend': ''
}

export const LABEL_TABS = {
  overview: 'Tổng quan',
  channel: 'Kênh',
  program: 'Chương trình',
  rating_by_minute: 'Rating theo phút',
  revenue: 'Doanh thu',
  effective: 'Hiệu quả',
  ad_monitoring_report: 'Ad monitoring report'
}

export const FLAGS = {
  "Mexico": "Mexico.png",
  "Hàn Quốc": "South-Korea.png",
  "Canada": "Canada.png",
  "Mỹ": "United-States.png",
  "Qatar": "Qatar.png",
  "Brazil": "Brazil.png",
  "Haiti": "Haiti.png",
  "Australia": "Australia.png",
  "Đức": "Germany.png",
  "Hà Lan": "Netherlands.png",
  "Bờ Biển Ngà": "Cote-dIvoire.png",
  "Thụy Điển": "Sweden.png",
  "Tây Ban Nha": "Spain.png",
  "Bỉ": "Belgium.png",
  "Ả Rập Xê Út": "Saudi-Arabia.png",
  "Iran": "Iran.png",
  "Pháp": "France.png",
  "Iraq": "Iraq.png",
  "Argentina": "Argentina.png",
  "Áo": "Austria.png",
  "Bồ Đào Nha": "Portugal.png",
  "Anh": "England.png",
  "Ghana": "Ghana.png",
  "Uzbekistan": "Uzbekistan.png",
  "CH Séc": "Czech-Republic.png",
  "Thụy Sĩ": "Switzerland.png",
  "Scotland": "Scotland.png",
  "Thổ Nhĩ Kỳ": "Turkey.png",
  "Ecuador": "Ecuador.png",
  "Tunisia": "Tunisia.png",
  "Uruguay": "Uruguay.png",
  "New Zealand": "New-Zealand.png",
  "Na Uy": "Norway.png",
  "Jordan": "Jordan.png",
  "Panama": "Panama.png",
  "Colombia": "Colombia.png",
  "Bosnia & Herzegovina": "Bosnia-and-Herzegovina.png",
  "Morocco": "Morocco.png",
  "Nam Phi": "South-Africa.png",
  "Curacao": "Curacao.png",
  "Nhật Bản": "Japan.png",
  "Paraguay": "Paraguay.png",
  "Senegal": "Senegal.png",
  "Cape Verde": "Cape-Verde.png",
  "Ai Cập": "Egypt.png",
  "Croatia": "Croatia.png",
  "CHDC Congo": "Democratic-Republic-of-the-Congo.png",
  "Algeria": "Algeria.png"
}

export const CHANNELS = {
  "VTV1": "vtv1.png",
  "VTV2": "vtv2.png",
  "VTV3": "vtv3.png",
  "VTV4": "vtv4.png",
  "VTV5": "vtv5.png",
  "VTV5 Tây Nguyên": "vtv5taynguyen.png",
  "VTV5 Tây Nam Bộ": "vtv5taynambo.png",
  "VTV6": "vtv6.png",
  "VTV7": "vtv7.png",
  "VTV8": "vtv8.png",
  "VTV9": "vtv9.png",
  "VTV10": "vtv10.png"
}

export const RESULT = {
  "Mexico - Nam Phi": "Mexico (2-0) Nam Phi",
  "Hàn Quốc - CH Séc": "Hàn Quốc (2-1) CH Séc",
  "Canada - Bosnia & Herzegovina": "Canada (1-1) Bosnia & Herzegovina",
  "Mỹ - Paraguay": "Mỹ (4-1) Paraguay",
  "Qatar - Thụy Sĩ": "Qatar (1-1) Thụy Sĩ",
  "Brazil - Morocco": "Brazil (1-1) Morocco",
  "Haiti - Scotland": "Haiti (0-1) Scotland",
  "Australia - Thổ Nhĩ Kỳ": "Australia (2-0) Thổ Nhĩ Kỳ",
  "Đức - Curacao": "Đức (7-1) Curacao",
  "Hà Lan - Nhật Bản": "Hà Lan (2-2) Nhật Bản",
  "Bờ Biển Ngà - Ecuador": "Bờ Biển Ngà (1-0) Ecuador",
  "Thụy Điển - Tunisia": "Thụy Điển (5-1) Tunisia",
  "Tây Ban Nha - Cape Verde": "Tây Ban Nha (0-0) Cape Verde",
  "Bỉ - Ai Cập": "Bỉ (1-1) Ai Cập",
  "Ả Rập Xê Út - Uruguay": "Ả Rập Xê Út (1-1) Uruguay",
  "Iran - New Zealand": "Iran (2-2) New Zealand",
  "Pháp - Senegal": "Pháp (3-1) Senegal",
  "Iraq - Na Uy": "Iraq (1-4) Na Uy",
  "Argentina - Algeria": "Argentina (3-0) Algeria",
  "Áo - Jordan": "Áo (3-1) Jordan",
  "Bồ Đào Nha - CHDC Congo": "Bồ Đào Nha (1-1) CHDC Congo",
  "Anh - Croatia": "Anh (4-2) Croatia",
  "Ghana - Panama": "Ghana (1-0) Panama",
  "Uzbekistan - Colombia": "Uzbekistan (1-3) Colombia",
  "CH Séc - Nam Phi": "CH Séc (1-1) Nam Phi",
  "Thụy Sĩ - Bosnia & Herzegovina": "Thụy Sĩ (4-1) Bosnia & Herzegovina",
  "Canada - Qatar": "Canada (6-0) Qatar",
  "Mexico - Hàn Quốc": "Mexico (1-0) Hàn Quốc",
  "Mỹ - Australia": "Mỹ (2-0) Australia",
  "Scotland - Morocco": "Scotland (0-1) Morocco",
  "Brazil - Haiti": "Brazil (3-0) Haiti",
  "Thổ Nhĩ Kỳ - Paraguay": "Thổ Nhĩ Kỳ (0-1) Paraguay",
  "Đức - Bờ Biển Ngà": "Đức (2-1) Bờ Biển Ngà",
  "Ecuador - Curacao": "Ecuador (0-0) Curacao",
  "Hà Lan - Thụy Điển": "Hà Lan (5-1) Thụy Điển",
  "Tunisia - Nhật Bản": "Tunisia (0-4) Nhật Bản",
  "Tây Ban Nha - Ả Rập Xê Út": "Tây Ban Nha (4-0) Ả Rập Xê Út",
  "Bỉ - Iran": "Bỉ (0-0) Iran",
  "Uruguay - Cape Verde": "Uruguay (2-2) Cape Verde",
  "New Zealand - Ai Cập": "New Zealand (1-3) Ai Cập",
  "Pháp - Iraq": "Pháp (3-0) Iraq",
  "Na Uy - Senegal": "Na Uy (3-2) Senegal",
  "Argentina - Áo": "Argentina (2-0) Áo",
  "Jordan - Algeria": "Jordan (1-2) Algeria",
  "Bồ Đào Nha - Uzbekistan": "Bồ Đào Nha (5-0) Uzbekistan",
  "Anh - Ghana": "Anh (0-0) Ghana",
  "Panama - Croatia": "Panama (0-1) Croatia",
  "Colombia - CHDC Congo": "Colombia (1-0) CHDC Congo",
  "CH Séc - Mexico": "CH Séc (0-3) Mexico",
  "Nam Phi - Hàn Quốc": "Nam Phi (1-0) Hàn Quốc",
  "Thụy Sĩ - Canada": "Thụy Sĩ (2-1) Canada",
  "Bosnia & Herzegovina - Qatar": "Bosnia & Herzegovina (3-1) Qatar",
  "Morocco - Haiti": "Morocco (4-2) Haiti",
  "Scotland - Brazil": "Scotland (0-3) Brazil",
  "Thổ Nhĩ Kỳ - Mỹ": "Thổ Nhĩ Kỳ (3-2) Mỹ",
  "Paraguay - Australia": "Paraguay (0-0) Australia",
  "Ecuador - Đức": "Ecuador (2-1) Đức",
  "Curacao - Bờ Biển Ngà": "Curacao (0-2) Bờ Biển Ngà",
  "Tunisia - Hà Lan": "Tunisia (1-3) Hà Lan",
  "Nhật Bản - Thụy Điển": "Nhật Bản (1-1) Thụy Điển",
  "New Zealand - Bỉ": "New Zealand (1-5) Bỉ",
  "Ai Cập - Iran": "Ai Cập (1-1) Iran",
  "Uruguay - Tây Ban Nha": "Uruguay (0-1) Tây Ban Nha",
  "Cape Verde - Ả Rập Xê Út": "Cape Verde (0-0) Ả Rập Xê Út",
  "Na Uy - Pháp": "Na Uy (1-4) Pháp",
  "Senegal - Iraq": "Senegal (5-0) Iraq",
  "Algeria - Áo": "Algeria (3-3) Áo",
  "Jordan - Argentina": "Jordan (1-3) Argentina",
  "Colombia - Bồ Đào Nha": "Colombia (0-0) Bồ Đào Nha",
  "CHDC Congo - Uzbekistan": "CHDC Congo (3-1) Uzbekistan",
  "Panama - Anh": "Panama (0-2) Anh",
  "Croatia - Ghana": "Croatia (2-1) Ghana"
}